"""Five more SOC simulations. Same tick schema as Night Shift."""

SIMS = [
{"id": "ransomware-3am", "title": "Ransomware at 3 AM",
 "briefing": "Saturday 03:10. Backup server reports odd jobs, then helpdesk gets the call nobody wants.",
 "ticks": [
  {"title": "03:10 — Shady invoice", "brief": "User opened 'invoice.pdf.exe' from an unknown sender an hour ago.",
   "auth": [], "web": [], "urls": ["http://192.0.2.55.verify-invoice.tk/doc"],
   "correct": ["Block IP / domain"], "why": "Double-extension carrier + look-alike host. Block, pull the mail, find who else got it.", "rooms": ["malware", "phish-email"]},
  {"title": "03:22 — RDP storm", "brief": "The infected host starts hammering the file server over RDP.",
   "auth": [f"Oct 11 03:22:{10+i:02d} soc sshd[4{i}]: Failed password for admin from 10.0.0.9 port 52{i:03d} ssh2" for i in range(6)],
   "web": [], "urls": [],
   "correct": ["Isolate host", "Block IP / domain"], "why": "Lateral movement in progress. Isolate the source box AND block it at the firewall.", "rooms": ["net-sec", "monitoring"]},
  {"title": "03:31 — Shadows deleted", "brief": "EDR: vssadmin delete shadows + thousands of file renames on FILE-02.",
   "auth": ["Oct 11 03:31:00 soc sshd[1]: Accepted password for backup from 10.0.0.9 port 52999 ssh2"],
   "web": ['10.0.0.9 - - [11/Oct/2026] "GET /share?f=..%2f..%2fboot.ini HTTP/1.1" 403 64'],
   "urls": [],
   "correct": ["Isolate host", "Escalate to L2"], "why": "Encryption phase. Isolate FILE-02 now; every minute is more shares locked.", "rooms": ["malware", "ir"]},
  {"title": "03:40 — Ransom note", "brief": "README_DECRYPT.txt appears on shares. Second site reports the same mail.",
   "auth": [], "web": [], "urls": ["http://192.0.2.55.verify-invoice.tk/pay"],
   "correct": ["Escalate to L2"], "why": "Declare the incident, start recovery from offline backups. Never pay first.", "rooms": ["ir"]},
  {"title": "04:05 — HR laptop?", "brief": "Alert: HR laptop beaconing to the same domain. Panic?",
   "auth": [], "web": ['10.0.0.21 - - [11/Oct/2026] "GET /benefits HTTP/1.1" 200 512'],
   "urls": [],
   "correct": ["Mark FP & close"], "why": "TRAP: normal benefits page, no IOCs. Verify the beacon claim before isolating HR mid-payroll.", "rooms": ["soc-ops"]},
 ]},
{"id": "insider-exfil", "title": "The Quiet Leaver",
 "briefing": "An engineer resigned Friday. Monday's logs look… industrious.",
 "ticks": [
  {"title": "Mon 01:12 — Night owl", "brief": "Resigned engineer logs in at 1 AM from home IP.",
   "auth": ["Oct 13 01:12:00 soc sshd[7]: Accepted password for eng-leaver from 198.51.100.9 port 51001 ssh2"],
   "web": [], "urls": [],
   "correct": ["Escalate to L2", "Do nothing"],
   "why": "Odd but possibly legit (deadline?). Note it, watch — acting now tips them off or punishes overtime.", "rooms": ["soc-ops"]},
  {"title": "Mon 01:40 — Bulk export", "brief": "Same session pulls /export?all=1 repeatedly, megabytes out.",
   "auth": [],
   "web": ['198.51.100.9 - - [13/Oct/2026] "GET /export?all=1&format=csv HTTP/1.1" 200 65536',
            '198.51.100.9 - - [13/Oct/2026] "GET /export?all=1&format=csv&page=2 HTTP/1.1" 200 65536'],
   "urls": [],
   "correct": ["Isolate host", "Escalate to L2"],
   "why": "Pattern flipped from odd to hostile: bulk customer pulls post-resignation. Contain + involve HR/legal.", "rooms": ["ir"]},
  {"title": "Mon 09:00 — Manager says…", "brief": "Manager: 'I asked them to finish the handover doc last night.'",
   "auth": [], "web": [], "urls": [],
   "correct": ["Mark FP & close", "Escalate to L2"],
   "why": "Plausible — but 130MB of CSV is no handover doc. Verify scope with DLP before closing.", "rooms": ["soc-ops"]},
  {"title": "Mon 09:20 — USB alarm", "brief": "EDR: 4GB written to unknown USB on their workstation.",
   "auth": [], "web": [], "urls": [],
   "correct": ["Isolate host", "Escalate to L2"],
   "why": "Second exfil channel confirmed. Isolate, preserve evidence, HR/legal own it from here.", "rooms": ["ir", "forensics"]},
 ]},
{"id": "supply-chain", "title": "Poisoned Update",
 "briefing": "Your monitoring vendor pushed an overnight update. By noon, two customers report odd beacons.",
 "ticks": [
  {"title": "Tue 12:05 — Intel lands", "brief": "Vendor advisory: 'update package may be trojanized, hashes inside.'",
   "auth": [], "web": [], "urls": [],
   "correct": ["Escalate to L2", "Block IP / domain"],
   "why": "Treat vendor compromise as real until disproven. Pull the hashes, hunt them, prep containment.", "rooms": ["ti"]},
  {"title": "Tue 12:40 — Beacon found", "brief": "One server POSTs 500 bytes hourly to an unknown host. Signed by the vendor binary.",
   "auth": [],
   "web": ['10.0.0.8 - - [14/Oct/2026] "POST /telemetry HTTP/1.1" 200 512'],
   "urls": [],
   "correct": ["Isolate host", "Escalate to L2"],
   "why": "Living-off-trusted-software: signatures won't save you. Isolate + hunt the same binary fleet-wide.", "rooms": ["threat-det"]},
  {"title": "Tue 13:15 — Second host?", "brief": "Same binary on a second host, but zero network anomalies.",
   "auth": ["Oct 14 13:15:00 soc sshd[3]: Accepted password for svc-mon from 10.0.0.9 port 51002 ssh2"],
   "web": [], "urls": [],
   "correct": ["Mark FP & close", "Isolate host"],
   "why": "Judgment call: same file WITHOUT behavior is low confidence. Either watch closely (FP-close with hunting) or isolate — both defensible; freezing is not.", "rooms": ["soc-ops"]},
  {"title": "Tue 14:00 — C2 confirmed", "brief": "Threat intel matches the beacon host to an active campaign.",
   "auth": [],
   "web": ['10.0.0.8 - - [14/Oct/2026] "POST /telemetry HTTP/1.1" 200 512',
            '10.0.0.8 - - [14/Oct/2026] "POST /telemetry HTTP/1.1" 200 512'],
   "urls": [],
   "correct": ["Block IP / domain", "Escalate to L2"],
   "why": "Confirmed C2: block at every layer, push detection fleet-wide, brief leadership.", "rooms": ["net-det", "ti"]},
 ]},
{"id": "bec-wire", "title": "The $47,000 Email",
 "briefing": "Finance pings you: 'CEO needs a wire sent in 20 minutes.' No malware — just words.",
 "ticks": [
  {"title": "10:02 — Urgent request", "brief": "Mail from 'CEO' (new Gmail): wire $47k to a new vendor today, 'keep it quiet'.",
   "auth": [], "web": [], "urls": ["http://ceo-urgent-pay.tk/invoice"],
   "correct": ["Block IP / domain"],
   "why": "Display-name spoof + urgency + secrecy + fresh domain = BEC. Block, preserve headers.", "rooms": ["phish-email"]},
  {"title": "10:11 — Pressure call", "brief": "'CEO' replies: 'Why hasn't it sent? Board is waiting.' Link side-loads an APK.",
   "auth": [], "web": [], "urls": ["http://ceo-urgent-pay.tk/app.apk"],
   "correct": ["Block IP / domain", "Reset passwords"],
   "why": "Escalating pressure plus a malicious APK. Block everything from this actor; reset finance creds in case of clicks.", "rooms": ["malware"]},
  {"title": "10:20 — Real CEO?", "brief": "The actual CEO walks past finance: 'What wire?'",
   "auth": [], "web": [], "urls": [],
   "correct": ["Escalate to L2", "Mark FP & close"],
   "why": "Confirmed spoof — but nothing paid. Escalate for the paper trail and an org-wide warning, or documented close.", "rooms": ["soc-ops"]},
  {"title": "10:35 — Second target", "brief": "HR got the same lure with a 'resume.zip' attached.",
   "auth": [], "web": [], "urls": ["http://ceo-urgent-pay.tk/resume.zip"],
   "correct": ["Block IP / domain", "Escalate to L2"],
   "why": "Campaign, not incident. Block + hunt all recipients + force the callback-verification process.", "rooms": ["ir"]},
 ]},
{"id": "ddos-smokescreen", "title": "Noise + Knife",
 "briefing": "Traffic alarms scream: 40x normal inbound. Somewhere in the noise hides the real attack.",
 "ticks": [
  {"title": "15:00 — Flood begins", "brief": "Edge routers melt: SYN flood from thousands of hosts.",
   "auth": [], "web": ['203.0.113.5 - - [15/Oct/2026] "GET / HTTP/1.1" 200 128'] * 3,
   "urls": [],
   "correct": ["Escalate to L2", "Do nothing"],
   "why": "Volumetric floods are the ISP/CDN's fight. Your job: hold the line AND watch for the quiet knife.", "rooms": ["net-det"]},
  {"title": "15:20 — Quiet probe", "brief": "One line in web logs while everyone stares at graphs: UNION SELECT on /login.",
   "auth": [],
   "web": ['198.51.100.77 - - [15/Oct/2026] "GET /login?u=1 UNION SELECT card FROM pay HTTP/1.1" 200 2048'],
   "urls": [],
   "correct": ["Block IP / domain", "Isolate host"],
   "why": "THE real attack wearing a DDoS costume. Block the SQLi source now.", "rooms": ["appsec"]},
  {"title": "15:35 — Credential replay", "brief": "Five logins from a fresh IP using creds like the probe worked.",
   "auth": [f"Oct 15 15:35:{20+i:02d} soc sshd[8{i}]: Failed password for shop from 198.51.100.77 port 53{i:03d} ssh2" for i in range(5)],
   "web": [], "urls": [],
   "correct": ["Block IP / domain", "Reset passwords"],
   "why": "Same actor pivoting to credential use. Block + force resets on targeted accounts.", "rooms": ["iam"]},
  {"title": "15:50 — All clear?", "brief": "Flood recedes. One dashboard still shows odd admin session from the flood window.",
   "auth": ["Oct 15 15:50:00 soc sshd[1]: Accepted password for admin from 10.0.0.6 port 51111 ssh2"],
   "web": [], "urls": [],
   "correct": ["Mark FP & close", "Escalate to L2"],
   "why": "Internal IP, no fails, plausible admin firefighting. Verify the session, then close — or escalate if anything smells.", "rooms": ["soc-ops"]},
 ]},
]
