"""20-lesson defensive curriculum. Each lesson: overview, points, one interactive
visual spec, hands-on task, 3-question quiz. ASCII only (Windows-console safe)."""

COURSE = [
{"id": "sec-fund", "area": "1. Security Fundamentals", "title": "CIA Triad, AAA & Defense-in-Depth",
 "overview": "Security rests on CIA: Confidentiality (only the right eyes), Integrity (data stays correct), Availability (systems stay up). AAA controls access: Authentication (who are you), Authorization (what may you do), Accounting (what did you do). No single control is perfect, so stack them: defense-in-depth.",
 "points": ["Least privilege: give the minimum access needed, nothing more",
   "Defense-in-depth: firewall + MFA + patching + backups — attacker must beat ALL",
   "Authentication proves identity (password/MFA); authorization sets permissions (RBAC)",
   "Controls come in 3 flavors: preventive, detective, corrective",
   "This tool's risk score is what happens when controls are missing"],
 "visual": {"kind": "picker", "label": "Pick a control type to see examples",
   "options": {"Preventive (stop it)": "Firewall rules, MFA, allowlists, least-privilege accounts. Example: blocking 203.0.113.9 after 5 fails.",
     "Detective (spot it)": "Log monitoring, IDS alerts, this tool's brute-force detector. Example: '6 Failed passwords' finding.",
     "Corrective (fix it)": "Patching, restoring backups, rotating leaked keys. Example: KEV-driven emergency patch."}},
 "try_it": "Analyze tab: run sample scan. Each HIGH = a control that failed. Note which control type would have stopped it.",
 "task_q": {"q": "A CCTV camera watching the server room is…", "opts": ["Preventive", "Detective", "Corrective"], "a": 1, "why": "It records evidence of events — detective."},
 "links": ["https://attack.mitre.org/", "https://www.cisa.gov/cybersecurity-training-exercises"],
 "quiz": [
  {"q": "Server room open to everyone violates…", "opts": ["Availability", "Confidentiality", "Accounting"], "a": 1, "why": "Unrestricted physical/logical access exposes data to wrong eyes."},
  {"q": "MFA login prompt is…", "opts": ["Corrective", "Preventive", "Detective"], "a": 1, "why": "It stops unauthorized logins before they happen."},
  {"q": "Authorization answers…", "opts": ["Who are you?", "What may you do?", "What did you do?"], "a": 1, "why": "Authentication = who; authorization = allowed actions; accounting = audit trail.", "hint": "Which A decides permissions?"},
  {"q": "Shared admin password, no logging. What breaks?", "opts": ["MFA", "Accountability", "Availability"], "a": 1, "why": "No attributable audit trail of who acted.", "hint": "Which A logs who acted?"},
  {"q": "Firewall + MFA + backups together are…", "opts": ["One control", "Defense in depth", "Compliance theater"], "a": 1, "why": "Stacked layers; attacker must beat them all.", "hint": "How many layers?"}]},

{"id": "net-sec", "area": "2. Network Security", "title": "Ports, Protocols & Perimeter",
 "overview": "Every network attack rides a protocol to a port. Defenders must know which ports should be open (443 web), which are dangerous from the internet (22 SSH, 3389 RDP, 445 SMB), and what encrypts traffic (HTTPS/TLS, VPN). Firewalls, proxies and segmentation shrink what attackers can reach.",
 "points": ["TCP 22/3389 + UDP exposed to internet = brute-force/ransomware magnet",
   "DNS translates names to IPs — attackers abuse it (tunneling, look-alike domains)",
   "HTTPS (443) encrypts; HTTP sends passwords in cleartext (our phishing scorer flags it)",
   "Segmentation: keep servers, users and guests on separate networks",
   "VPN/proxy: encrypted remote access + controlled egress"],
 "visual": {"kind": "table", "search": "Filter ports (try 'remote' or 'mail')",
  "columns": ["Port", "Service", "Exposure note"],
  "rows": [["22", "SSH", "Remote admin — never public without VPN/MFA"], ["53", "DNS", "Abused for tunneling; monitor odd queries"],
   ["80", "HTTP", "Cleartext web — redirect to 443"], ["443", "HTTPS", "Encrypted web — the safe default"],
   ["3389", "RDP", "Top ransomware vector — never public"], ["445", "SMB", "Worm spread (WannaCry) — block at edge"],
   ["25/587", "SMTP", "Mail send — spoofing target, needs SPF/DKIM/DMARC"], ["3306", "MySQL", "Database — app-servers only"]]},
 "try_it": "Analyze tab: find the brute-force source IP. Which port was it guessing against? (Hint: auth logs = SSH/22.)",
 "task_q": {"q": "A scan shows RDP (3389) open to the internet. Your call?", "opts": ["Ignore it", "Flag HIGH — restrict immediately", "Note as info"], "a": 1, "why": "Public RDP is a top ransomware entry point."},
 "links": ["https://owasp.org/www-project-top-ten/"],
 "quiz": [
  {"q": "Most dangerous to expose to the internet?", "opts": ["443 HTTPS", "3389 RDP", "53 DNS"], "a": 1, "why": "RDP brute-force is a top ransomware entry point."},
  {"q": "HTTPS protects you by…", "opts": ["Hiding the site name", "Encrypting traffic in transit", "Blocking viruses"], "a": 1, "why": "TLS encrypts data; phishing sites can also use HTTPS though."},
  {"q": "Segmentation means…", "opts": ["Faster wifi", "Splitting networks to limit spread", "More admins"], "a": 1, "why": "Breach in one segment cannot freely reach others.", "hint": "What limits roaming?"},
  {"q": "Port 445 open to the internet means…", "opts": ["File sharing exposed — worm risk", "Faster downloads", "Nothing"], "a": 0, "why": "SMB exposure enabled worms like WannaCry.", "hint": "Which worm loved 445?"},
  {"q": "A VPN mainly gives you…", "opts": ["Encrypted remote access", "Antivirus", "Faster internet"], "a": 0, "why": "A tunnel, not a guard.", "hint": "Tunnel, not guard."}]},

{"id": "endpoint", "area": "3. Endpoint Security", "title": "Hardening Laptops & Servers",
 "overview": "Endpoints (laptops, servers) are where attackers land. Defense = harden the system (remove what attackers use), keep an antivirus/EDR watching behavior, and patch fast — most exploited bugs in the KEV catalog already have patches.",
 "points": ["EDR watches behavior (odd process chains); antivirus matches known files",
   "Patch management: KEV-listed bugs first, then CVSS-high",
   "No daily admin accounts; UAC/sudo prompts on",
   "Host firewall on; USB/removable media policy set",
   "Tested backups: ransomware-proof only if offline + restorable"],
 "visual": {"kind": "checklist", "items": ["EDR/antivirus installed + updating", "OS auto-patches enabled", "Host firewall ON", "Daily-driver account is NOT admin", "Backups exist AND were test-restored"]},
 "try_it": "Score yourself on the checklist. Anything unchecked is your personal HIGH finding.",
 "task_q": {"q": "A host runs SMBv1, unpatched for 6 months. Biggest risk?", "opts": ["Slow boot", "Wormable exploit foothold", "Loud fan"], "a": 1, "why": "Unpatched + SMBv1 = WannaCry-style spread."},
 "links": ["https://www.cisa.gov/knownExploitedVulnerabilitiesCatalog"],
 "quiz": [
  {"q": "EDR vs antivirus: EDR mainly…", "opts": ["Matches file hashes", "Detects suspicious behavior chains", "Speeds up the PC"], "a": 1, "why": "EDR correlates process/network behavior, not just signatures."},
  {"q": "Patch priority #1?", "opts": ["Newest CVE", "KEV-listed exploited bugs", "Lowest CVSS"], "a": 1, "why": "KEV = actually exploited in the wild."},
  {"q": "A backup that was never test-restored is…", "opts": ["Fine", "Possibly useless when needed", "Illegal"], "a": 1, "why": "Corrupt/partial backups are discovered at the worst moment.", "hint": "When do you discover rot?"},
  {"q": "Daily work as admin risks…", "opts": ["Speed", "Malware inherits the crown", "Bigger screen"], "a": 1, "why": "Everything you run, including malware, runs as king.", "hint": "Whose rights do viruses get?"},
  {"q": "Untested backup = …", "opts": ["Fine", "A hope, not a plan", "Illegal"], "a": 1, "why": "Restore drills turn hope into certainty.", "hint": "Hope or certainty?"}]},

{"id": "iam", "area": "4. Identity & Access Security", "title": "IAM, MFA, SSO & Least Privilege",
 "overview": "Identity is the new perimeter: stolen logins cause most breaches. IAM = the right person gets the right access. MFA blocks password-guessing (the brute-force in our labs), SSO centralizes logins, RBAC/privileged-access keeps admins scoped.",
 "points": ["MFA everywhere, esp. email/VPN/admin — authenticator app or passkey beats SMS",
   "SSO: one strong login instead of 20 weak ones",
   "RBAC: permissions follow job roles, reviewed regularly",
   "Privileged accounts: separate admin IDs, vaulted, time-bound",
   "This tool's brute-force lesson exists because passwords alone fail"],
 "visual": {"kind": "scenario", "q": "A contractor needs production DB access for a 2-day migration. Best call?",
   "options": ["Grant permanent DB admin — faster", "Time-bound read-write role, revoked after 2 days", "Share the DBA's password temporarily"],
   "answer": 1, "why": "Least privilege + time-bound: access auto-expires, actions stay attributable."},
 "try_it": "Tutor: ask 'MFA vs SMS codes' then check your own email/VPN for MFA status.",
 "task_q": {"q": "An ex-employee's account is still active 3 months later. Failed process?", "opts": ["Patching", "Offboarding / access review", "Backups"], "a": 1, "why": "Joiner-mover-leaver reviews must revoke promptly."},
 "links": ["https://cheatsheetseries.owasp.org/"],
 "quiz": [
  {"q": "Strongest common second factor?", "opts": ["SMS code", "Authenticator app / passkey", "Security question"], "a": 1, "why": "SMS is SIM-swappable; app/passkeys resist phishing better."},
  {"q": "RBAC means access based on…", "opts": ["Seniority", "Job role", "Location"], "a": 1, "why": "Roles bundle exactly the permissions a job needs."},
  {"q": "Shared admin passwords are bad because…", "opts": ["Hard to type", "No accountability + linger after exits", "Cost money"], "a": 1, "why": "You cannot tell WHO acted, or revoke one person.", "hint": "Who acted? Can you revoke one?"},
  {"q": "SSO's main benefit?", "opts": ["One strong login", "No passwords anywhere ever", "Free VPN"], "a": 0, "why": "Twenty weak logins become one strong, guarded login.", "hint": "Twenty weak vs one strong?"},
  {"q": "Stale ex-employee account violates…", "opts": ["Patching", "Joiner-mover-leaver", "Backups"], "a": 1, "why": "Leaver reviews must revoke promptly.", "hint": "Which process removes leavers?"}]},

{"id": "monitoring", "area": "5. Security Monitoring", "title": "Logs: Where Attacks Leave Footprints",
 "overview": "Attackers cannot act without touching logs: failed logins, web requests, DNS lookups. Monitoring = collecting the right logs and actually reading the anomalies. Every detector in this tool is a mini monitoring rule.",
 "points": ["Auth logs: brute-force signal ('Failed password' x N from one IP)",
   "Windows: Event 4625 failed logon / 4624 success; Linux: /var/log/auth.log",
   "Web logs: SQLi/XSS probes hide in request lines",
   "Network/DNS logs: odd domains, beaconing intervals",
   "Keep clocks synced (NTP) or timelines lie"],
 "visual": {"kind": "table", "search": "Filter (try 'windows' or 'web')",
  "columns": ["Log source", "Attack it reveals", "Example"],
  "rows": [["Linux auth.log", "Brute-force", "Failed password for root from 203.0.113.9"], ["Windows Security 4625", "Password guessing", "Failed logon, unknown user"],
   ["Web access log", "SQLi / XSS probes", "GET /?id=1 UNION SELECT…"], ["DNS logs", "C2 / tunneling", "Hourly queries to random subdomain"], ["Firewall logs", "Scanning", "One IP hitting many ports"]]},
 "try_it": "Analyze tab: open data/sample_auth.log — count fails per IP by eye before hitting Analyze.",
 "task_q": {"q": "50 fails then a 3 AM success from a new country. This is…", "opts": ["True positive — escalate", "Confirmed false positive", "Routine noise"], "a": 0, "why": "Fail-burst + odd-hour success = classic compromise signal."},
 "links": [],
 "quiz": [
  {"q": "6 'Failed password' from one IP suggests…", "opts": ["Backup running", "Brute-force (T1110)", "Disk full"], "a": 1, "why": "Repeated failures from one source = guessing."},
  {"q": "Windows failed-logon event ID?", "opts": ["4625", "4624", "404"], "a": 0, "why": "4625 = failed, 4624 = successful logon."},
  {"q": "Why NTP sync matters?", "opts": ["Faster logs", "Correct event ordering across hosts", "Saves disk"], "a": 1, "why": "Skewed clocks scramble multi-host timelines.", "hint": "What scrambles timelines?"},
  {"q": "Windows event 4624 means…", "opts": ["Failed logon", "Successful logon", "Reboot"], "a": 1, "why": "4624 success pairs with 4625 failure — watch odd-hour 4624s.", "hint": "Pair of 4625?"},
  {"q": "Alerting on log silence means…", "opts": ["Broken rule", "Possibly killed logging", "Quiet network"], "a": 1, "why": "Attackers blind you first; silence is a signal.", "hint": "Who benefits from blindness?"}]},

{"id": "siem", "area": "6. SIEM", "title": "Splunk, Sentinel & Correlation",
 "overview": "A SIEM (Splunk, Microsoft Sentinel, QRadar) ingests logs from everywhere, then correlation rules turn noise into alerts ('5 fails + success from new country = incident'). Dashboards show posture; queries (SPL/KQL) let you hunt.",
 "points": ["Ingestion: forward endpoint, firewall, cloud logs to one place",
   "Correlation: combine weak signals into one strong alert",
   "Tune rules or drown in false positives — our threshold slider teaches this",
   "Dashboards: risk posture at a glance (like our gauge)",
   "SentinelLearn is a pocket SIEM: ingest, detect, score, alert"],
 "visual": {"kind": "code", "lang": "SPL / KQL idea", "code": "# Splunk (SPL): brute-force hunt\nindex=auth \"Failed password\"\n| stats count by src_ip | where count > 5\n\n# Sentinel (KQL): same idea\nSigninLogs | where ResultType != 0\n| summarize fails=count() by IPAddress | where fails > 5",
  "note": "Same logic as our brute-force detector — threshold 5. Lower it = more alerts AND more noise."},
 "try_it": "Analyze tab: move the threshold slider 2 vs 10 and compare HIGH counts. That is SIEM tuning.",
 "task_q": {"q": "Rule fires 1000x/min on one noisy IP, all FPs. Tuning call?", "opts": ["Raise threshold to 5000", "Keep rule + add allowlist for the noisy host", "Delete the rule"], "a": 1, "why": "Suppress the known-benign source, keep protection for the rest."},
 "links": [],
 "quiz": [
  {"q": "Correlation rule value?", "opts": ["More logs", "Weak signals combined into strong alerts", "Cheaper storage"], "a": 1, "why": "Single events are noise; patterns are incidents."},
  {"q": "Threshold too low causes…", "opts": ["Missed attacks", "Alert fatigue from false positives", "Faster queries"], "a": 1, "why": "Analysts start ignoring a noisy console."},
  {"q": "SPL/KQL are used to…", "opts": ["Install agents", "Query and hunt across logs", "Encrypt data"], "a": 1, "why": "They are the SIEM search languages.", "hint": "Search languages for what?"},
  {"q": "Correlation example?", "opts": ["Bigger disks", "Fails + odd success = takeover", "More agents"], "a": 1, "why": "Weak signals combined into one strong alert.", "hint": "Weak signals combined?"},
  {"q": "A rule with 90% FP rate should…", "opts": ["Enforce harder", "Tune or allowlist the noise", "Delete the SIEM"], "a": 1, "why": "Precision first; noisy rules get ignored.", "hint": "What feeds alert fatigue?"}]},

{"id": "soc-ops", "area": "7. SOC Operations", "title": "Triage Like an L1 Analyst",
 "overview": "SOC L1 = first responder to alerts: validate true vs false positive, scope impact, set severity, contain or escalate to L2. Speed + notes matter — the next analyst continues from your ticket.",
 "points": ["True positive or false positive? Evidence first, gut second",
   "Severity (damage) vs priority (response order) — related, not equal",
   "Scope: one host or whole subnet? One account or many?",
   "Escalate with evidence + timeline, never bare alerts",
   "Document everything in the ticket — future-you will thank you"],
 "visual": {"kind": "stepper", "steps": ["1. Collect: alert + raw evidence", "2. Validate: TP or FP? check logs", "3. Scope: hosts, users, data touched", "4. Severity: LOW/MED/HIGH/CRITICAL", "5. Act: contain low-level or escalate L2", "6. Document: ticket with timeline"]},
 "try_it": "Analyze tab: triage findings with filters, Mark reviewed, watch Triaged X/Y hit 100%.",
 "task_q": {"q": "Ransomware behavior on the file server + adware on guest wifi. First?", "opts": ["Adware first", "Ransomware on file server", "Alphabetical order"], "a": 1, "why": "Blast radius decides priority: critical asset + active encryption."},
 "links": [],
 "quiz": [
  {"q": "First triage step?", "opts": ["Reboot server", "Validate with evidence", "Call the CEO"], "a": 1, "why": "Confirm TP vs FP before acting."},
  {"q": "Severity vs priority?", "opts": ["Same thing", "Damage vs response order", "Only managers care"], "a": 1, "why": "Critical damage can still queue behind an active outbreak."},
  {"q": "Good escalation includes…", "opts": ["Alert screenshot only", "Evidence + scope + timeline", "Your lunch plans"], "a": 1, "why": "L2 continues from your context, not from zero.", "hint": "What does L2 need to continue?"},
  {"q": "Severity vs priority?", "opts": ["Same thing", "Damage vs response order", "Manager-only terms"], "a": 1, "why": "Ransomware outranks adware even when both are high.", "hint": "Ransomware vs adware order?"},
  {"q": "A complete ticket has…", "opts": ["Screenshot only", "Evidence + timeline + reasoning", "Jokes"], "a": 1, "why": "Future analysts (and auditors) need the full story.", "hint": "What survives shift change?"}]},

{"id": "ir", "area": "8. Incident Response", "title": "The 6-Phase Response Cycle",
 "overview": "Incident response (NIST SP 800-61) runs Prepare, Detect & Analyze, Contain, Eradicate, Recover, Lessons-Learned. Skipping phases (e.g. recovering before eradicating) lets attackers walk back in.",
 "points": ["Preparation: playbooks, contacts, backups BEFORE the incident",
   "Containment first (isolate host), then eradicate (kill persistence)",
   "Eradicate before recover — or reinfection is guaranteed",
   "Preserve evidence: image first if legal/HR action possible",
   "Lessons-learned turns one incident into permanent defenses"],
 "visual": {"kind": "stepper", "steps": ["1. Prepare: playbooks, roles, backups", "2. Detect & Analyze: confirm + scope", "3. Contain: isolate host, block IOCs", "4. Eradicate: remove malware/persistence", "5. Recover: restore, monitor closely", "6. Lessons: fix root cause forever"]},
 "try_it": "Take one HIGH from Analyze and walk it through all 6 phases on paper.",
 "task_q": {"q": "Host still beacons during eradication. You…", "opts": ["Recover it now", "Re-contain + hunt persistence", "Wipe the logs"], "a": 1, "why": "Active C2 means eradication failed — back to containment."},
 "links": [],
 "quiz": [
  {"q": "Why contain before eradicate?", "opts": ["Looks busy", "Stop spread while you investigate", "Saves logs"], "a": 1, "why": "Isolation freezes damage during analysis."},
  {"q": "Recovering before eradicating causes…", "opts": ["Faster closure", "Reinfection", "Better logs"], "a": 1, "why": "Persistence left behind re-activates."},
  {"q": "Lessons-learned exists to…", "opts": ["Blame L1", "Convert incident into permanent fix", "Fill paperwork"], "a": 1, "why": "Root-cause fixes prevent repeats.", "hint": "What stops repeats?"},
  {"q": "Recovering before eradicating causes…", "opts": ["Faster closure", "Reinfection", "Bonus pay"], "a": 1, "why": "The backdoor is still home.", "hint": "Did the backdoor leave?"},
  {"q": "Memory matters, so you pull…", "opts": ["The plug (fastest)", "The network cable (keep RAM)", "Either"], "a": 1, "why": "RAM dies at power-off; cable keeps it.", "hint": "What dies at power-off?"}]},

{"id": "threat-det", "area": "9. Threat Detection", "title": "IOCs, IOAs, TTPs & Hunting",
 "overview": "Detections range from brittle (file hash = changes hourly) to durable (behavior = attacker must retool). Hunt proactively for TTPs (MITRE techniques) instead of waiting for IOC alerts.",
 "points": ["IOC: atomic evidence — IP, hash, domain (expires fast)",
   "IOA: behavior artifacts — encoded PowerShell, odd parent process",
   "TTP: adversary method — e.g. T1110 brute-force (durable detection)",
   "Pyramid of Pain: higher layers hurt attackers more to change",
   "Hunt hypothesis-first: 'if ransomware, expect T1486 + shadow-copy deletes'"],
 "visual": {"kind": "picker", "label": "Pick a detection layer",
  "options": {"IOC — hash/IP/domain": "Example: block 203.0.113.9. Pain to attacker: trivial (new IP in seconds).",
   "IOA — behavior artifact": "Example: 'powershell -enc' from Word. Pain: must rewrite tooling.",
   "TTP — technique (T1110)": "Example: alert on ANY password-guessing pattern. Pain: must change method entirely."}},
 "try_it": "Map each Analyze finding to IOC (the IP/URL) and TTP (T1110/T1190/T1566).",
 "task_q": {"q": "Hunt hypothesis for phishing-delivered RAT?", "opts": ["Email lure + T1566 + child processes of Outlook", "Reinstall printers", "Buy a new firewall"], "a": 0, "why": "Hypothesis names lure, technique, and where to look."},
 "links": ["https://attack.mitre.org/"],
 "quiz": [
  {"q": "Most durable detection?", "opts": ["File hash", "TTP-based behavior rule", "Single IP block"], "a": 1, "why": "Behaviors survive re-hashes and new IPs."},
  {"q": "T1566.002 is…", "opts": ["A CVE", "Spearphishing-link technique", "A firewall"], "a": 1, "why": "ATT&CK technique IDs describe HOW attackers act."},
  {"q": "Threat hunting starts with…", "opts": ["A hypothesis", "A reboot", "A purchase"], "a": 0, "why": "Hypothesis -> data -> confirm/refute.", "hint": "Guess, then verify?"},
  {"q": "Hash changes daily, method stays. Track the…", "opts": ["Hash harder", "Behavior / TTP", "File size"], "a": 1, "why": "What survives rehashing.", "hint": "What survives rehash?"},
  {"q": "An IOA looks like…", "opts": ["A file hash", "Encoded PowerShell from Word", "A file size"], "a": 1, "why": "Behavior artifact, not an atom.", "hint": "Behavior or atom?"}]},

{"id": "malware", "area": "10. Malware Defense", "title": "Ransomware, Trojans & Sandboxes",
 "overview": "Malware = any hostile code. Ransomware encrypts for ransom, trojans pose as legit apps, worms self-spread, RATs give remote control. Defense: block delivery (email/web), detonate unknowns in a sandbox, keep offline backups.",
 "points": ["Never pay: funds crime, decryption often fails anyway",
   "Delivery is usually phishing or malicious ads/downloads",
   "Sandbox: run suspicious files isolated, watch behavior",
   "Indicators: odd persistence (Run keys), C2 beacons, mass file renames",
   "APK/PDF checks in File Check tab catch common carriers"],
 "visual": {"kind": "picker", "label": "Pick a malware type",
  "options": {"Ransomware": "Encrypts files, demands crypto. Kill-chain ends at Impact (T1486). Defense: offline backups + patch.",
   "Trojan": "Looks legit, hides backdoor. Defense: only official stores, check signatures.",
   "Worm": "Self-spreads (SMB/RDP). Defense: segment + patch (WannaCry lesson).",
   "RAT / Spyware": "Silent control/theft. Defense: EDR + least privilege + egress filtering.",
   "Wiper": "Destroys, no ransom. Defense: same as ransomware, plus IR rehearsal."}},
 "try_it": "File Check tab: scan any APK/PDF and read which carrier flags fire.",
 "task_q": {"q": "Attachment 'invoice.pdf.exe' arrives. Correct read?", "opts": ["Open to verify", "Double-extension carrier — sandbox + report", "Forward to the team"], "a": 1, "why": "Executable masquerading as document = classic trojan delivery."},
 "links": [],
 "quiz": [
  {"q": "First ransomware priority?", "opts": ["Pay fast", "Isolate + restore from clean backup", "Delete logs"], "a": 1, "why": "Containment + clean recovery beats funding criminals."},
  {"q": "Sandbox purpose?", "opts": ["Store backups", "Detonate files safely to observe", "Speed up PCs"], "a": 1, "why": "Isolated execution reveals behavior without risk."},
  {"q": "Top malware delivery?", "opts": ["USB in parking lot only", "Phishing + malicious downloads", "Bluetooth"], "a": 1, "why": "Email/web lures scale cheapest for attackers.", "hint": "Cheapest scale for criminals?"},
  {"q": "vssadmin delete shadows signals…", "opts": ["An update", "Ransomware final phase", "Backup success"], "a": 1, "why": "Killing recovery before encrypting.", "hint": "Why kill shadow copies?"},
  {"q": "Pay the ransom because…", "opts": ["Guaranteed decrypt", "Never — funds crime, often fails", "It's faster"], "a": 1, "why": "No guarantee + marks you for repeats.", "hint": "Who profits?"}]},

{"id": "phish-email", "area": "11. Phishing & Email Security", "title": "Spot the Lure, Read the Headers",
 "overview": "Phishing steals credentials via deception. Defenses: technical (SPF/DKIM/DMARC verify senders, filters strip payloads) + human (verify out-of-band, hover links, MFA so stolen passwords fail).",
 "points": ["SPF: which servers may send for a domain; DKIM: cryptographic signature; DMARC: policy tying them",
   "Check: sender vs Reply-To, urgency, link target, attachments",
   "Spear phishing = researched target; whaling = executives",
   "Report buttons feed filters that protect everyone",
   "Our phishing scorer grades the same tricks automatically"],
 "visual": {"kind": "scenario", "q": "Email: 'IT-Desk: mailbox full, verify at http://192.0.2.9.verify-login.tk/inbox'. You…?",
  "options": ["Click and log in fast", "Hover/inspect, report, verify via official portal", "Reply asking if legit"],
  "answer": 1, "why": "Bare IP + urgency + look-alike domain = textbook phish. Verify out-of-band."},
 "try_it": "Analyze tab URLs box: paste 2 legit + 2 phishy links, compare scores.",
 "task_q": {"q": "Reply-To differs from From and the link target mismatches. Verdict?", "opts": ["Legit newsletter", "Phish — report it", "Reply asking if legit"], "a": 1, "why": "Mismatched identity + link = report, never engage."},
 "links": ["https://attack.mitre.org/techniques/T1566/002/"],
 "quiz": [
  {"q": "DMARC builds on…", "opts": ["SPF + DKIM", "Antivirus", "VPN"], "a": 0, "why": "DMARC aligns and enforces SPF/DKIM results."},
  {"q": "Strongest post-click safety net?", "opts": ["Long password", "MFA + password manager", "Caps lock"], "a": 1, "why": "Manager won't fill on fake domains; MFA blocks reuse."},
  {"q": "Spear phishing differs by…", "opts": ["More images", "Targeted research on victim", "Bigger fonts"], "a": 1, "why": "Personalization is what raises success rates.", "hint": "What raises success rates?"},
  {"q": "DMARC p=reject means…", "opts": ["More spam", "Fakes get rejected", "Slower mail"], "a": 1, "why": "Enforcement, not observation.", "hint": "Enforce or observe?"},
  {"q": "BEC defense that actually works?", "opts": ["Reply fast", "Callback known numbers + dual approval", "Trust display names"], "a": 1, "why": "Out-of-band verification breaks the con.", "hint": "Which channel is trusted?"}]},

{"id": "vuln-mgmt", "area": "12. Vulnerability Management", "title": "CVE, CVSS & Patch Like a Pro",
 "overview": "Find it (scan: Nessus/OpenVAS), rank it (CVSS score + KEV exploited-status + asset value), fix it (patch/config), verify. KEV membership beats raw CVSS — exploited bugs jump the queue.",
 "points": ["CVE = named bug; CVSS = 0-10 severity; KEV = exploited-now list",
   "Scan authenticated (with creds) for true results",
   "Prioritize: internet-facing + KEV + critical asset",
   "Remediation != mitigation: patch removes, workaround reduces",
   "Rescan to close the loop — unverified fixes reopen"],
 "visual": {"kind": "table", "search": "Filter bands",
  "columns": ["CVSS", "Band", "Action"],
  "rows": [["9.0-10.0", "Critical", "Emergency change, patch now"], ["7.0-8.9", "High", "Patch this cycle"], ["4.0-6.9", "Medium", "Scheduled window"], ["0.1-3.9", "Low", "Batch with next release"], ["Any + KEV", "EXPLOITED", "Jumps queue regardless of score"]]},
 "try_it": "Trending (CLI: python main.py trending): pick a CVE, look it up on NVD, note CVSS vs KEV status.",
 "task_q": {"q": "Which jumps the patch queue regardless of score?", "opts": ["KEV-listed CVE", "Newest CVE", "Lowest CVSS"], "a": 0, "why": "Actively exploited = patch window is already open for attackers."},
 "links": ["https://nvd.nist.gov/", "https://www.cisa.gov/knownExploitedVulnerabilitiesCatalog"],
 "quiz": [
  {"q": "CVE-2024-1234 with KEV listing + CVSS 5.5 → treat as…", "opts": ["Low, ignore", "High priority (exploited)", "Info only"], "a": 1, "why": "Active exploitation outranks the medium score."},
  {"q": "Authenticated scans are better because…", "opts": ["Faster", "See missing patches/configs inside", "Cheaper"], "a": 1, "why": "Credentials reveal what external scans miss."},
  {"q": "Mitigation vs remediation?", "opts": ["Same", "Reduce risk vs remove cause", "Slower vs faster"], "a": 1, "why": "WAF rule mitigates; code patch remediates.", "hint": "Band-aid vs cure?"},
  {"q": "Authenticated scans win because…", "opts": ["Speed", "See patches/configs inside", "Looks cool"], "a": 1, "why": "Credentials reveal what outside scans miss.", "hint": "What do creds reveal?"},
  {"q": "SBOMs help with…", "opts": ["Speed", "Hidden library risks (Log4j)", "Fonts"], "a": 1, "why": "You can't patch libraries you can't see.", "hint": "Where do deps hide?"}]},

{"id": "ti", "area": "13. Threat Intelligence", "title": "Actors, Feeds & ATT&CK",
 "overview": "TI turns scattered IOCs into decisions: WHO attacks, HOW (TTPs), and WHAT to do. Consume feeds (CISA KEV, abuse.ch), map to ATT&CK, and push blocks/detections before the actor reaches you.",
 "points": ["Strategic (exec), operational (campaigns), tactical (IOCs) — different consumers",
   "Actor types: cybercrime, APT/nation-state, hacktivist, insider",
   "TTPs > IOCs: behaviors outlive IPs/hashes",
   "OSINT tab = mini TI workbench (DNS, certs, reputation)",
   "Always validate feed IOCs before auto-blocking (FP risk)"],
 "visual": {"kind": "picker", "label": "Pick an actor type",
  "options": {"Cybercrime (ransomware gangs)": "Motive: money. TTPs: phishing -> RDP -> T1486 encryption. Defense: backups + MFA + patch.",
   "APT / nation-state": "Motive: espionage. TTPs: zero-days, living-off-land, long dwell. Defense: hunting + segmentation + logging.",
   "Hacktivist": "Motive: message. TTPs: defacement, DDoS. Defense: WAF + capacity + comms plan.",
   "Malicious insider": "Motive: varies. TTPs: legit creds abused. Defense: least privilege + UEBA + offboarding."}},
 "try_it": "OSINT tab: look up a domain, note which TI question each result answers (who/how/what).",
 "task_q": {"q": "Feed IOC is 2 years old with zero sightings. Action?", "opts": ["Auto-block everywhere", "Treat as low confidence / retire", "Email the CEO"], "a": 1, "why": "Stale intel decays; blocking it risks false positives."},
 "links": ["https://attack.mitre.org/"],
 "quiz": [
  {"q": "Best long-lived intel?", "opts": ["Yesterday's hash", "TTPs mapped to ATT&CK", "One IP"], "a": 1, "why": "Methods persist; atoms rotate."},
  {"q": "Tactical intel consumer?", "opts": ["Board", "SOC detection engineers", "HR"], "a": 1, "why": "They turn IOCs/TTPs into rules and blocks."},
  {"q": "Auto-block feeds blindly risks…", "opts": ["Faster SOC", "False-positive outages", "More budget"], "a": 1, "why": "Stale/mistaken IOCs break legit business.", "hint": "What breaks when IOCs rot?"},
  {"q": "Two-year-old IOC, zero sightings:", "opts": ["Block everywhere", "Retire / low confidence", "Frame it"], "a": 1, "why": "Intel decays; act accordingly.", "hint": "What rots?"},
  {"q": "Best intel product?", "opts": ["5000-row dump", "One-page brief + actions", "Rumors"], "a": 1, "why": "Decisions beat data volume.", "hint": "What gets read?"}]},

{"id": "net-det", "area": "14. Network Detection", "title": "IDS/IPS, NDR & Wireshark",
 "overview": "When endpoints lie (or lack agents), the network tells truth: IDS/IPS match malicious traffic, NDR baselines behavior, and Wireshark lets you read packets by hand during investigations.",
 "points": ["IDS detects, IPS blocks inline — tune to avoid self-DoS",
   "NDR: anomaly baselines (beaconing, odd hours, data spikes)",
   "Wireshark display filters zoom to evil fast",
   "DNS analysis: long random labels, high query rates = tunneling",
   "Full packets beat flow summaries for forensics"],
 "visual": {"kind": "code", "lang": "Wireshark display filters", "code": "dns.qry.name contains \"tk\"\nhttp.request.method == POST\ntcp.port == 4444\nip.addr == 203.0.113.9\ndns.flags.response == 0",
  "note": "Type these in Wireshark's filter bar during the sample pcap exercise: isolate DNS, POST exfil, odd ports."},
 "try_it": "Tutor: ask 'how do I spot C2 beaconing?' then list 3 packet signs.",
 "task_q": {"q": "Best first Wireshark filter for suspected DNS tunneling?", "opts": ["dns", "tcp.port == 80 only", "eth.addr"], "a": 0, "why": "Isolate DNS first, then look for long random labels."},
 "links": [],
 "quiz": [
  {"q": "IDS vs IPS?", "opts": ["Same box", "Detect-only vs inline block", "Old vs new"], "a": 1, "why": "IPS sits in traffic path and can drop."},
  {"q": "Beaconing suggests…", "opts": ["Streaming", "Malware checking in regularly", "Gaming"], "a": 1, "why": "Regular intervals to one host = C2 heartbeat."},
  {"q": "DNS tunneling sign?", "opts": ["Short queries", "Long random labels, high volume", "No queries"], "a": 1, "why": "Data smuggled inside subdomain strings.", "hint": "Where is data hidden?"},
  {"q": "IDS vs IPS?", "opts": ["Same box", "Detect-only vs inline block", "Old vs new"], "a": 1, "why": "IPS sits in the traffic path.", "hint": "Which sits in traffic?"},
  {"q": "Long random DNS labels + volume = …", "opts": ["Streaming", "Tunneling suspect", "Gaming"], "a": 1, "why": "Classic exfil pattern.", "hint": "Smuggled where?"}]},

{"id": "appsec", "area": "15. Application Security", "title": "OWASP Top 10 Essentials",
 "overview": "Most breaches start in apps: injection, broken access control, XSS. Fix categories with patterns (parameterize queries, deny-by-default, escape output) and verify with checklists — exactly what our web detectors demo.",
 "points": ["Injection (SQLi): never concatenate user input into queries",
   "Broken Access Control: deny by default, check every object",
   "XSS: escape output + Content-Security-Policy",
   "Security Misconfiguration: defaults, debug pages, open S3",
   "Scan in CI + review Top 10 yearly — apps drift insecure"],
 "visual": {"kind": "table", "search": "Filter (try 'inject' or 'access')",
  "columns": ["Risk", "Fix pattern"],
  "rows": [["Injection (SQLi)", "Parameterized queries / ORM"], ["Broken Access Control", "Deny-by-default + per-object checks"],
   ["XSS", "Output escaping + CSP header"], ["Security Misconfiguration", "Hardened baselines, no defaults"], ["Vulnerable Components", "SBOM + patch cadence"]]},
 "try_it": "Analyze tab web log: each SQLi/XSS line = one OWASP row violated. Name them.",
 "task_q": {"q": "Found /actuator/heapdump publicly readable. Category?", "opts": ["Injection", "Security misconfiguration", "XSS"], "a": 1, "why": "Debug endpoint exposed = misconfiguration, leaks secrets."},
 "links": ["https://owasp.org/www-project-top-ten/", "https://cheatsheetseries.owasp.org/"],
 "quiz": [
  {"q": "SQLi fix?", "opts": ["Longer passwords", "Parameterized queries", "Bigger server"], "a": 1, "why": "Separates code from data."},
  {"q": "XSS primary fix?", "opts": ["Escape output + CSP", "Rename files", "Block Google"], "a": 0, "why": "Neutralizes injected script at render."},
  {"q": "Broken access control example?", "opts": ["Slow page", "Changing /user/12 to /user/13 shows others' data", "404 page"], "a": 1, "why": "Missing per-object authorization (IDOR).", "hint": "Whose data shows?"},
  {"q": "IDOR fix?", "opts": ["Longer URLs", "Server-side ownership checks", "Hide buttons"], "a": 1, "why": "Only the server can enforce ownership.", "hint": "Who must verify owner?"},
  {"q": "Stored XSS is worst because…", "opts": ["Longer code", "Hits every viewer", "Uses CSS"], "a": 1, "why": "One injection, all visitors.", "hint": "Who gets hit?"}]},

{"id": "cloud", "area": "16. Cloud Security", "title": "Don't Leak the Bucket",
 "overview": "Cloud breaches are usually misconfiguration, not cloud broken: public storage, 0.0.0.0/0 security groups, root without MFA, no logging, leaked keys in repos. Secure the control plane first.",
 "points": ["MFA on root/admin + no long-lived access keys lying around",
   "Storage private by default; audit public exposures",
   "Security groups: least-port, never 0.0.0.0/0 admin ports",
   "Enable audit logging (CloudTrail/Activity Log) + alerts",
   "Scan IaC and repos for secrets before deploy"],
 "visual": {"kind": "checklist", "items": ["Root/admin MFA ON", "No public storage buckets", "No 0.0.0.0/0 on 22/3389/3306", "Audit logging enabled + reviewed", "No secrets committed in code"]},
 "try_it": "Mentally audit one checklist item for any cloud account you own.",
 "task_q": {"q": "Bucket 'prod-backups' is public and indexed. First step?", "opts": ["Tweet about it", "Make private + rotate exposed secrets", "Delete the account"], "a": 1, "why": "Close exposure, then assume listed contents are compromised."},
 "links": [],
 "quiz": [
  {"q": "Most common cloud breach cause?", "opts": ["Zero-days in hypervisor", "Customer misconfiguration", "Solar flares"], "a": 1, "why": "Shared-responsibility: you own the config."},
  {"q": "0.0.0.0/0 on SSH means…", "opts": ["Fast login", "Whole internet can try SSH", "Free VPN"], "a": 1, "why": "Unrestricted source = global brute-force."},
  {"q": "Leaked API key first step?", "opts": ["Ignore", "Revoke + rotate + check logs", "Rename file"], "a": 1, "why": "Kill abuse window, then assess damage.", "hint": "What closes the abuse window?"},
  {"q": "Root without MFA is…", "opts": ["Fine", "Top priority fix", "Faster logins"], "a": 1, "why": "Keys to the kingdom with one factor.", "hint": "Keys to the kingdom?"},
  {"q": "0.0.0.0/0 on port 22 means…", "opts": ["Fast SSH", "The world can knock", "Free VPN"], "a": 1, "why": "Unrestricted source = global brute-force.", "hint": "Who is 0.0.0.0/0?"}]},

{"id": "hardening", "area": "17. Security Hardening", "title": "Lock Down Windows & Linux",
 "overview": "Hardening removes attacker options: fewer services, tighter firewall, secure baselines (CIS), controlled privileges. Do it with checklists and automation so every host matches.",
 "points": ["Disable what you don't use (Telnet, SMBv1, unused roles)",
   "Firewall default-deny inbound; allow only needed ports",
   "CIS benchmarks = copy-paste secure baselines",
   "Remove local admins; LAPS-style unique passwords",
   "Re-harden after changes — drift is constant"],
 "visual": {"kind": "checklist", "items": ["Unneeded services/roles removed", "Firewall default-deny inbound", "CIS baseline applied", "SMBv1 / Telnet gone", "Local admin count minimal"]},
 "try_it": "Run services list on your machine; name one thing you could disable.",
 "task_q": {"q": "Telnet is enabled for switch management. Action?", "opts": ["Leave for legacy use", "Disable, use SSH", "Expose to internet"], "a": 1, "why": "Telnet sends credentials in cleartext — no safe use remains."},
 "links": [],
 "quiz": [
  {"q": "Default-deny means…", "opts": ["Block everything except allowed", "Allow all, log some", "No firewall"], "a": 0, "why": "Fail-closed beats fail-open."},
  {"q": "CIS benchmarks are…", "opts": ["Malware", "Community secure baselines", "Firewalls"], "a": 1, "why": "Step-by-step lockdown guides per OS/app."},
  {"q": "Why remove SMBv1?", "opts": ["Slow", "Exploited by worms, superseded", "Uses disk"], "a": 1, "why": "WannaCry-era protocol with no safe use left.", "hint": "Which worm loved it?"},
  {"q": "CIS benchmarks are…", "opts": ["Malware", "Community secure baselines", "A firewall brand"], "a": 1, "why": "Step-by-step lockdown guides.", "hint": "Guides for what?"},
  {"q": "Friday-evening hardening…", "opts": ["Best time", "Never — no rollback window", "Fastest"], "a": 1, "why": "Breakage with nobody around.", "hint": "Who helps at midnight?"}]},

{"id": "forensics", "area": "18. Digital Forensics", "title": "Artifacts & Timelines",
 "overview": "Forensics answers WHAT happened: disk artifacts (MFT, registry, prefetch), browser history, event logs, memory for live malware. Build a timeline — cause must precede effect.",
 "points": ["Order of volatility: memory first, disk later",
   "Registry Run keys + Startup = persistence favorites",
   "Prefetch/Shimcache prove a program RAN (not just existed)",
   "Browser history/downloads timestamp user actions",
   "Timeline ties it together: phish click -> payload -> C2"],
 "visual": {"kind": "picker", "label": "Pick an artifact to learn what it proves",
  "options": {"MFT ($STANDARD_INFORMATION)": "File create/modify/access times — spot mass-encryption timing.",
   "Registry Run keys": "Auto-start programs — classic persistence. Check HKCU/HKLM Run.",
   "Prefetch": "Proves execution + run count + last run — great for 'was malware launched?'",
   "Browser history": "User-side story: phish link click time, download source.",
   "Memory (RAM)": "Live-only evidence: injected processes, keys, C2 sessions. Capture before power-off."}},
 "try_it": "Tutor: ask 'MFT vs prefetch — what does each prove?' and compare.",
 "task_q": {"q": "Must pull the plug now, no time. Grab first?", "opts": ["RAM capture", "Desktop screenshot", "The mouse"], "a": 0, "why": "Volatile memory vanishes at power-off — order of volatility."},
 "links": [],
 "quiz": [
  {"q": "Capture first?", "opts": ["Disk image", "Volatile memory", "Router box"], "a": 1, "why": "RAM disappears at power-off."},
  {"q": "Prefetch proves…", "opts": ["File existed", "Program executed (+times)", "User is admin"], "a": 1, "why": "Execution evidence with timestamps."},
  {"q": "Timeline purpose?", "opts": ["Pretty charts", "Order events to prove cause-effect", "Fill disk"], "a": 1, "why": "Sequence reveals the attack story.", "hint": "What proves cause-effect?"},
  {"q": "Analyze originals directly?", "opts": ["Yes, faster", "No — hashed copies only", "Only Mondays"], "a": 1, "why": "Court admissibility needs custody.", "hint": "What keeps court happy?"},
  {"q": "Prefetch proves…", "opts": ["Existence", "Execution + count", "Ownership"], "a": 1, "why": "Ran, how often, when.", "hint": "Ran or just sat there?"}]},

{"id": "automation", "area": "19. Security Automation", "title": "Python, Playbooks & SOAR",
 "overview": "Analysts automate the boring: enrich IOCs, open tickets, block-and-log. Start with Python/PowerShell scripts, grow into SOAR playbooks with human approval gates for dangerous actions.",
 "points": ["Automate enrichment first (low risk): WHOIS, VT links, geo",
   "Keep blocks behind approval until FP rate is known",
   "Playbooks = code + process: trigger, steps, rollback",
   "Log every automated action for audit",
   "This tool's detectors ARE automation: rules replacing eyeballs"],
 "visual": {"kind": "code", "lang": "Python enrichment snippet", "code": "import hashlib\nsha = hashlib.sha256(open('evil.apk','rb').read()).hexdigest()\nprint(f\"https://www.virustotal.com/gui/search/{sha}\")\n# low-risk automation: build the report link, human clicks",
  "note": "Pattern: machine gathers, human decides. Auto-block only mature, low-FP rules."},
 "try_it": "Run test-email (CLI): you just triggered an automated alert path manually.",
 "task_q": {"q": "New auto-block rule, FP rate unknown. Deploy as?", "opts": ["Enforce globally", "Alert-only + approval first", "Delete it"], "a": 1, "why": "Prove safety in monitor mode before handing it the trigger."},
 "links": [],
 "quiz": [
  {"q": "Automate first?", "opts": ["Auto-delete mailboxes", "Enrichment + links", "Auto-firewall everything"], "a": 1, "why": "Enrichment helps without outage risk."},
  {"q": "Approval gates exist because…", "opts": ["Slow attackers", "Auto-blocks can cause outages via FPs", "Auditors like clicks"], "a": 1, "why": "Wrong auto-block = self-inflicted downtime."},
  {"q": "Playbook includes…", "opts": ["Only code", "Trigger + steps + rollback + owner", "Memes"], "a": 1, "why": "Response must be repeatable and reversible.", "hint": "Repeatable + reversible?"},
  {"q": "Playbook secrets live in…", "opts": ["Inline code", "Vaults", "Team chat"], "a": 1, "why": "Code leaks; vaults rotate.", "hint": "Where do keys live?"},
  {"q": "Auto-block, FP rate unknown:", "opts": ["Enforce now", "Alert-only first", "Delete the tool"], "a": 1, "why": "Prove safety before handing the trigger.", "hint": "What outage risk?"}]},

{"id": "frameworks", "area": "20. Security Frameworks", "title": "ATT&CK, NIST, CIS & Kill Chain",
 "overview": "Frameworks give shared language: ATT&CK (how attackers act), NIST CSF (how programs mature: Govern/Identify/Protect/Detect/Respond/Recover), CIS Controls (prioritized safeguards), Kill Chain (7 attack stages to break).",
 "points": ["ATT&CK: tactics -> techniques (T1110) -> procedures",
   "NIST CSF 2.0: six functions incl. Govern",
   "CIS IG1: minimum must-dos for small teams",
   "Kill Chain: break ANY stage to stop the attack",
   "Map every finding here to its ATT&CK technique — do it in Analyze"],
 "visual": {"kind": "table", "search": "Filter frameworks",
  "columns": ["Framework", "Answers"],
  "rows": [["MITRE ATT&CK", "HOW do attackers act? (T1110, T1566)"], ["NIST CSF 2.0", "Is our PROGRAM complete? (GV/ID/PR/DE/RS/RC)"],
   ["CIS Controls v8", "WHAT to do first? (IG1 essentials)"], ["Cyber Kill Chain", "WHERE to break the attack? (7 stages)"],
   ["NIST SP 800-61", "HOW to respond? (6 IR phases)"]]},
 "try_it": "Open Resources tab: visit ATT&CK, find T1110, read its mitigations.",
 "task_q": {"q": "CISO asks 'are we covering all bases?' Best lens?", "opts": ["One Kill Chain stage", "NIST CSF functions review", "A single CVE"], "a": 1, "why": "CSF reviews the whole program: govern through recover."},
 "links": ["https://attack.mitre.org/", "https://d3fend.mitre.org/"],
 "quiz": [
  {"q": "T1110 lives in…", "opts": ["NIST CSF", "MITRE ATT&CK", "CIS IG1"], "a": 1, "why": "Technique IDs are ATT&CK's language."},
  {"q": "NIST CSF Govern (GV) covers…", "opts": ["Firewalls", "Strategy, roles, risk appetite", "Antivirus"], "a": 1, "why": "Governance steers the whole program."},
  {"q": "Kill Chain value?", "opts": ["Longer reports", "Break one stage, stop attack", "More tools"], "a": 1, "why": "Defense needs only one successful break.", "hint": "How many breaks to win?"},
  {"q": "D3FEND provides…", "opts": ["More attacks", "Countermeasures per technique", "Free laptops"], "a": 1, "why": "Engineered defense counterpart of ATT&CK.", "hint": "Defense side of ATT&CK?"},
  {"q": "CSF Govern covers…", "opts": ["Firewalls", "Strategy, roles, risk appetite", "Antivirus"], "a": 1, "why": "Leadership accountability layer.", "hint": "Who steers?"}]},
]
