"""Depth layer: deep-dives, mistakes, interview prep, commands per lesson. ASCII only."""

DEPTH = {
"sec-fund": {
 "deep_dive": ["Defense-in-depth works because attackers chain weaknesses: phish the password (breaks confidentiality), escalate via missing patch (breaks integrity controls), encrypt backups too (breaks availability). Each layer you add removes an entire class of cheap attacks. Mature teams draw this as overlapping rings: policy (what is allowed), technical (MFA, firewall, EDR), physical (badges, locks), and human (training, reporting). A gap in ANY ring is where incidents start - most breaches trace to a missing basic, not a exotic zero-day.",
  "AAA in practice: a VPN login prompts for password + authenticator code (authentication), drops you into role-based groups (authorization), and writes every connection to a central log (accounting). When an alert fires, accounting is what lets you answer 'who did what, when'. Least privilege is the daily application: interns read tickets, seniors approve changes, nobody holds standing domain-admin."],
 "mistakes": ["Treating compliance checklists as security (audits pass, breaches still happen)", "Buying tools before defining what each control must stop", "Shared admin passwords with no expiry or logging"],
 "interview": [{"q": "Explain CIA with one example each.", "a": "Confidentiality: encrypted customer DB readable only by app role. Integrity: signed software updates verified before install. Availability: dual power + tested backups keeping checkout online during outage."}, {"q": "Preventive vs detective vs corrective?", "a": "Preventive stops (MFA), detective spots (SIEM alert on 6 fails), corrective restores (backup). Name which one each company control is."}],
 "commands": ["# who has admin? (Windows)\nnet localgroup administrators", "# last logons (Linux)\nlast -a | head -20"]},

"net-sec": {
 "deep_dive": ["TCP's three-way handshake (SYN, SYN-ACK, ACK) is why stealth scans work: a SYN scan never completes the handshake, so sloppy logging misses it. DNS is the phonebook attackers poison (cache poisoning) or tunnel through (encoding stolen data in subdomain labels - check for very long random labels and high query rates). Firewalls filter by 5-tuple (source/dest IP, ports, protocol); a WAF adds Layer-7 understanding (it knows what SQLi looks like inside HTTP). Segmentation limits blast radius: web servers live in a DMZ that can neither see nor be seen by the internal DB network except through one guarded hole.",
  "Encryption reality check: TLS 1.2+ with valid certs protects in transit, but it does NOT prove honesty - phishing kits deploy HTTPS in minutes. Always verify the domain, the sender, and the context separately. VPN choice matters: WireGuard/IPsec for site links, client VPN with device checks for remote staff, never free VPNs that monetize traffic."],
 "mistakes": ["Exposing RDP/SSH/SMB to the internet 'temporarily' (scanners find it in minutes)", "Trusting the padlock alone on phishing pages", "Flat network: user laptop reaches production DB directly"],
 "interview": [{"q": "SYN scan vs full connect scan?", "a": "SYN sends SYN, reads SYN-ACK/RST, never completes handshake - stealthier, needs raw sockets. Connect completes TCP handshake - logged everywhere, needs no privileges."}, {"q": "How do you spot DNS tunneling?", "a": "Long random subdomains, high query volume to one domain, odd record types (TXT/NULL), beacon-like regularity."}],
 "commands": ["# what is listening? (Linux)\nss -tulpn | head -30", "# test a port from outside\nTest-NetConnection host -Port 443  # PowerShell"]},

"endpoint": {
 "deep_dive": ["Antivirus matches known-bad (hashes, signatures) in milliseconds; EDR records behavior chains (Word -> powershell -enc -> outbound 4444) and scores them. Modern attacks live off the land - using built-in tools instead of malware files - so signature-only setups go blind. Patching order that works: internet-facing + KEV-listed first (days), then CVSS-high (weeks), then the rest. EDR telemetry (process parent/child, command lines, network flows) is also your best forensic source; keep 30-90 days hot.",
  "Backups decide ransomware outcomes: 3-2-1 (three copies, two media, one offline/offsite), encryption at rest, and a TESTED restore (a backup you never restored is a hope, not a plan). Application allowlisting on servers flips the model: nothing runs unless approved - brutal to operate, devastating to attackers."],
 "mistakes": ["Admin rights for daily work (every click runs as king)", "Backups on the same network, never test-restored", "SMBv1/Telnet left on 'because legacy'"],
 "interview": [{"q": "EDR alert: powershell -enc from WINWORD.exe. Walk through it.", "a": "Treat as malicious until proven otherwise: isolate host, capture command line + parent chain, check outbound connections, hunt the same pattern fleet-wide, find the lure document."}, {"q": "Patch Tuesday vs KEV emergency?", "a": "Routine cycle for normal CVEs; out-of-band for KEV-listed or actively exploited in your sector."}],
 "commands": ["# EDR-style hunt: odd parents (PowerShell)\nGet-WinEvent -FilterHashtable @{LogName='Security'; Id=4688} | Select-Object -First 5", "# SMBv1 still on?\nGet-WindowsOptionalFeature -Online | Where FeatureName -like '*SMB1*'"]},

"iam": {
 "deep_dive": ["Passwords fail for three mathematical reasons: reuse (one leak unlocks many doors), guessability (humans pick patterns), and phishability (a fake page harvests them). MFA adds a second, DIFFERENT proof: something you have (phone key) or are (fingerprint). Authenticator apps and passkeys resist phishing because the proof is bound to the real domain; SMS codes do not (SIM-swap + interception). SSO reduces 20 weak logins to one strong one - but makes that one login crown jewels, so protect it with phishing-resistant MFA and conditional access (unknown device + new country = step up or block).",
  "RBAC done right: roles mirror job functions, access reviews every quarter remove drift, privileged actions require just-in-time elevation with recorded sessions. Break-glass accounts exist for IdP outages - sealed, monitored, tested yearly. Joiner-mover-leaver automation is the unglamorous control that kills most stale-access findings."],
 "mistakes": ["SMS-only MFA on admin/email accounts", "Standing domain-admin for daily work", "Orphaned accounts of exited staff with mailbox + VPN intact"],
 "interview": [{"q": "Why is SMS MFA weak?", "a": "SIM-swap moves the number to attacker SIM; SS7 interception; no phishing binding - codes work on fake sites. Prefer authenticator/passkeys."}, {"q": "Design contractor access for 2 days.", "a": "Time-bound role, least privilege, MFA enforced, all actions logged, auto-expiry + manager attestation."}],
 "commands": ["# Entra ID: users with permanent admin roles (needs AzureAD module)\n# Get-AzureADDirectoryRole | % { Get-AzureADDirectoryRoleMember -ObjectId $_.ObjectId }", "# find stale local accounts (Windows)\nnet user | findstr /i active"]},

"monitoring": {
 "deep_dive": ["Good monitoring answers four questions fast: WHO (user/IP), WHAT (action), WHERE (asset), WHEN (synced time). Linux auth.log gives SSH brute-force in one grep; Windows Security log 4625/4624 gives logon success/failure with workstation names; web access logs hide injection probes in query strings; DNS logs reveal tunneling and look-alike domains; firewall logs show scanning (one IP, many ports = recon). NTP sync underpins everything - a 5-minute skew between hosts scrambles multi-host timelines.",
  "Rule design that survives: start from attacker behavior (T1110 = N fails + success from new ASN), set thresholds from YOUR baseline (not vendor defaults), add allowlists for known-benign noise (vulnerability scanners, monitoring), and alert on ABSENCE too (domain controller gone silent = logging killed?). Review every rule quarterly: precision (TP rate) and coverage (which ATT&CK techniques lack rules)."],
 "mistakes": ["Collecting logs nobody reads (compliance theater)", "Vendor-default thresholds (alert storms or silence)", "Unsynced clocks across hosts"],
 "interview": [{"q": "Alert: 50 fails then success at 3 AM from new country. Steps?", "a": "Validate (check user travel/claims), scope (what did session touch), contain (reset creds, kill sessions), escalate with timeline."}, {"q": "Why alert on log absence?", "a": "Attackers kill logging to blind you; a silent critical host is itself an indicator."}],
 "commands": ["# brute-force hunt (Linux)\ngrep 'Failed password' /var/log/auth.log | awk '{print $(NF-3)}' | sort | uniq -c | sort -nr | head", "# Windows failed logons\nGet-WinEvent -FilterHashtable @{LogName='Security'; Id=4625} -MaxEvents 10"]},

"siem": {
 "deep_dive": ["A SIEM's real job is joining weak signals: failed logons (endpoint) + impossible travel (IdP) + new forwarding rule (mailbox) = one account-takeover incident, not three alerts. Ingestion normalizes everything into common fields (src_ip, user, action) so one query spans vendors. Correlation rules need a lifecycle: draft from ATT&CK technique, test against 30 days of history, run alert-only to measure precision, then enforce with runbook attached. Dashboards serve two masters: execs (risk trend, MTTR) and hunters (technique coverage heatmap, top noisy rules).",
  "Cost reality: ingestion is priced per GB, so teams choose: full fidelity on auth/EDR/DNS, sampled or dropped debug chatter, with drop-rules documented. Content-as-code (rules in git, reviewed, tested) separates mature SIEMs from click-ops consoles. SentinelLearn mirrors this loop at pocket scale: ingest sample logs, detect with rules, score risk, alert by mail."],
 "mistakes": ["Enforcing untested rules (outage by automation)", "No rule tuning loop (alert fatigue, ignored console)", "Ingesting everything, affording nothing"],
 "interview": [{"q": "Write a brute-force rule in SPL or KQL.", "a": "SPL: index=auth 'Failed password' | stats count by src_ip | where count>5. KQL: SigninLogs | where ResultType!=0 | summarize fails=count() by IPAddress | where fails>5."}, {"q": "Rule fires 500x/day, all FP. Fix?", "a": "Find the benign pattern, allowlist it narrowly, keep the rule; track precision before/after."}],
 "commands": ["# Splunk: top failing users\nindex=auth 'Failed password' | stats count by user | sort - count", "# KQL: impossible travel sketch\n# SigninLogs | where ResultType==0 | summarize by UserPrincipalName, Location"]},

"soc-ops": {
 "deep_dive": ["L1 triage is applied skepticism: assume nothing, verify with logs. Severity measures DAMAGE (data touched? how many hosts?), priority measures ORDER (active ransomware outranks dormant adware even if both are 'high'). Scoping decides the response size: one host = isolate + reimage; whole subnet = declare incident, war room. Escalation quality is a skill: alert + raw evidence + what you already checked + your hypothesis + what you need. L2 should continue, never restart.",
  "Tickets are organizational memory: timeline, IOCs, actions with timestamps, and the reasoning ('closed as FP because...'). Shift handover reads like a medical chart. Metrics that matter: mean time to acknowledge/respond, FP rate per rule (feedback to engineers), escalation acceptance rate (are your escalations good?). Burnout defense is operational: tune noisy rules instead of heroically clicking through them."],
 "mistakes": ["Closing alerts without evidence ('looks fine')", "Escalating bare screenshots with no context", "Treating severity and priority as the same thing"],
 "interview": [{"q": "Walk me through a phishing alert triage.", "a": "Check headers/sender/links in sandbox, scope recipients, check clicks/executions, contain (block URL, reset creds if clicked), ticket with timeline."}, {"q": "Ransomware on fileserver vs adware on guest wifi?", "a": "Fileserver first: blast radius (critical asset + active encryption) sets priority."}],
 "commands": ["# quick scope: who else talked to evil IP? (Linux)\ngrep '203.0.113.9' /var/log/* 2>/dev/null | cut -d: -f1 | sort -u", "# ticket-ready timeline header\n# WHO WHAT WHERE WHEN + evidence links"]},

"ir": {
 "deep_dive": ["NIST SP 800-61 phases exist because order matters: containing (isolate host, block IOCs at firewall/mail) BEFORE eradicating (kill persistence, close the hole) stops spread while you work; eradicating BEFORE recovering prevents instant reinfection - the classic failure is restoring from a backup that still contains the backdoor. Evidence handling runs in parallel: image disks with write-blockers, capture memory first (volatility order), keep chain-of-custody notes if legal or HR action is possible.",
  "War-room triggers (example): ransomware behavior, data-exfil indicators, multiple hosts, or customer data involved. Comms discipline: one spokesperson, pre-approved holding statements, no speculation in writing. Tabletop exercises twice a year rehearse decisions (who can pull the plug on production?) so the real incident is the second time, not the first. The lessons-learned report must name root causes AND funded fixes with owners - otherwise it is theater."],
 "mistakes": ["Recovering before eradicating (guaranteed reinfection)", "Rebooting before memory capture (evidence destroyed)", "Silent solo response with no ticket or comms"],
 "interview": [{"q": "Ransomware confirmed on one server. First 3 actions?", "a": "Isolate host (pull network, not power, if memory capture possible), declare incident + page IR, preserve evidence then block IOCs."}, {"q": "Why lessons-learned with owners?", "a": "Unowned findings rot; owned + funded fixes prevent repeats - track repeat-incident rate."}],
 "commands": ["# isolate Linux host fast (drop all but SSH from jump box)\n# iptables -P INPUT DROP  # CAREFUL: lab only, have console access", "# memory capture (winpmem-style)\n# winpmem.exe memdump.raw  # then analyze offline"]},

"threat-det": {
 "deep_dive": ["Detection engineering is programming against adversaries: each rule encodes an assumption ('brute-force looks like N fails + success'). Attackers adapt, so rules need tests - atomic checks that fire the rule on demand (like unit tests for security). Pyramid of Pain ranks what you detect on: hashes and IPs (attacker changes in seconds), domains and tools (days of work), TTPs like T1110 (months of retooling). Threat hunting flips the model: start from a hypothesis ('if ransomware is here, shadow copies die first'), gather data, confirm or refute, then encode the win as a rule.",
  "Coverage thinking: list the ATT&CK techniques relevant to YOUR stack, mark which have tested detections, and work the gaps by risk. Behavioral analytics (UEBA) add baselines - impossible travel, odd hours,体积 anomalies - but need tuning per population (admins travel; service accounts should not). Feed every confirmed detection back: new IOCs to blocklists, new behaviors to rules."],
 "mistakes": ["Hash-only ransomware rules (rotated hourly)", "Hunting without hypothesis (random log diving)", "Detections with no tests (silently broken for months)"],
 "interview": [{"q": "Design a durable brute-force detection.", "a": "Behavioral: fail-velocity per account+source, success-after-fail, new-ASN success; alert on pattern, not single IP; test with simulated spray."}, {"q": "IOC vs IOA vs TTP?", "a": "IOC: atomic (hash/IP, expires fast). IOA: artifact of behavior (encoded PS from Word). TTP: method (T1110) - most durable."}],
 "commands": ["# hunt: rare child processes of Office (Sysmon E1/E7 idea)\n# index=sysmon ParentImage=*WINWORD* | stats count by Image", "# beacon check: regular intervals to one host\n# index=proxy | stats count, dc(dest) by src | where count>100"]},

"malware": {
 "deep_dive": ["Execution is the chokepoint: every payload must RUN. That is why application allowlisting, macro policies, and EDR process rules punch above their weight - they guard the moment of truth. Persistence is the second chokepoint: Run keys, scheduled tasks, services, WMI subscriptions, browser extensions. Learn the 5 Windows spots by heart and you will find most commodity malware. C2 is the third: DNS/HTTPS beacons at regular intervals, odd user-agents, long sleeps. Ransomware adds a fourth: mass file renames + shadow-copy deletion (vssadmin) + ransom notes - any ONE of these is a high-fidelity alert.",
  "Sandbox detonation shows intent safely: submit attachments/URLs, watch process tree + network + dropped files for 5 minutes. For triage without a sandbox, static checks (our File Check tab: APK permissions/signatures, PDF JS/Launch flags, double extensions) filter the obvious. Never pay: decryption tools often fail, payment marks you for repeats, and it funds the ecosystem - restore from tested offline backups instead."],
 "mistakes": ["Paying the ransom first, investigating never", "Opening 'invoice.pdf.exe' to 'check what it is'", "No backup restore test until the crisis"],
 "interview": [{"q": "vssadmin delete shadows + mass renames. Meaning?", "a": "Ransomware final phase: isolate host NOW, check backups offline, declare incident."}, {"q": "Sandbox vs static scan?", "a": "Static is fast triage (flags, metadata); sandbox observes live behavior - use both, in that order."}],
 "commands": ["# hunt persistence: autoruns locations (PowerShell)\nGet-CimInstance Win32_StartupCommand | Select Name, Command", "# strings peek at payload (Linux)\nstrings suspect.bin | grep -iE 'http|powershell|cmd\\.exe' | head"]},

"phish-email": {
 "deep_dive": ["Phishing wins on three levers: authority (boss/IT/bank), urgency (suspended in 24h), and secrecy (don't tell anyone). Technical defenses attack each: SPF declares which servers may send for your domain, DKIM cryptographically signs mail, DMARC enforces alignment and tells receivers to quarantine/reject fakes (p=reject is the goal). Gateway rewriting + sandbox detonation catch payloads; report buttons turn every user into a sensor feeding better filters. Human layer: verify out-of-band (call the known number, open the official app yourself), hover to reveal link targets, and let MFA + password managers absorb the failures (manager won't fill on look-alike domains).",
  "BEC (business email compromise) deserves special fear: no malware, just a spoofed executive asking finance to wire funds. Defense is process: payment changes require voice callback to KNOWN numbers + dual approval. Spear-phishing raises the stakes with researched personal details - train high-risk roles (finance, HR, execs) with realistic simulations and measure report-rate, not just click-rate."],
 "mistakes": ["Clicking to 'verify if legit' (verification IS the compromise)", "Trusting display names and padlocks", "Replying to ask the attacker"],
 "interview": [{"q": "Design DMARC rollout.", "a": "Publish p=none + aggregate reports, fix legit senders (marketing, SaaS), move to quarantine then reject, monitor rua reports."}, {"q": "BEC wire-fraud defense?", "a": "Out-of-band callback on known numbers + dual approval for payment changes; no exceptions for 'urgent' executive mail."}],
 "commands": ["# inspect raw headers (look for)\n# Received-SPF, DKIM-Signature, DMARC policy, Reply-To vs From, Return-Path", "# check domain age/reputation\n# whois suspect.tk | grep -i created"]},

"vuln-mgmt": {
 "deep_dive": ["CVSS scores three angles: exploitability (attack vector, complexity, privileges, user interaction), impact (confidentiality/integrity/availability), and scope (does it jump systems, like container escapes). A 9.8 needing no clicks on an internet box is an emergency; the same 9.8 on an isolated test VM is Tuesday. KEV membership overrides math: someone IS exploiting it, so your window is already open. Authenticated scans (with creds) see missing patches and bad configs; unauthenticated scans see only the outside - run both, compare, and mind the gap.",
  "Program mechanics: asset inventory first (you cannot patch what you cannot list), risk-based SLAs (KEV internet-facing in days, highs in the cycle), exception register with expiry dates (risk acceptance, not risk ignorance), and verification rescans that actually close tickets. SBOMs extend this to dependencies: one bad library (Log4j taught everyone) hides in a hundred apps. Report trend lines (mean age of criticals, % KEV within SLA), not raw counts."],
 "mistakes": ["Patching by CVSS alone, ignoring KEV + exposure", "Unauthenticated-only scans (blind to real gaps)", "Fixes without rescan (tickets closed on hope)"],
 "interview": [{"q": "Internet 9.8 non-KEV vs internal 7.1 KEV. First?", "a": "Argue exposure x exploitation: typically internet 9.8 first for blast radius, but KEV means active use - escalate both, sequence by asset value; no single right answer, show reasoning."}, {"q": "Mitigation vs remediation example?", "a": "WAF rule blocking Log4j patterns = mitigation; upgrading log4j = remediation. Do both, in that order."}],
 "commands": ["# quick exposure check (Linux)\nss -tulpn | grep -E '0.0.0.0|:::'", "# NVD lookup pattern\n# https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2024-XXXX"]},

"ti": {
 "deep_dive": ["Good intel answers a decision: block this? hunt that? patch now? The intel cycle (direction, collection, processing, analysis, dissemination) starts from leadership's fears, not from feeds. Pyramid thinking applies: stable TTPs (phishing -> RDP -> ransomware) outlive IOCs (today's hash). Sector matters: hospitals face ransomware affiliates, fintech faces Magecart-style skimmers and mule networks, everyone faces commodity phish kits. OSINT (DNS history, cert transparency, passive DNS, reputation DBs) is TI you can do today - our OSINT tab is exactly that workbench.",
  "Sharing multiplies value: ISACs and peer groups trade IOCs/TTPs faster than vendors publish. Validate before auto-blocking (confidence + expiry on every feed item; stale IOCs cause self-inflicted outages). Measure outcomes, not volume: campaigns blocked pre-impact, detection lead-time gained, hunts launched from intel. A one-page weekly brief (actors, relevant TTPs, actions taken) beats a 5000-row IOC dump nobody reads."],
 "mistakes": ["Auto-blocking raw feeds (stale IOC outage)", "Collecting IOCs with no dissemination path", "Ignoring sector-specific threats for generic lists"],
 "interview": [{"q": "Turn a CISA alert into action.", "a": "Extract TTPs + IOCs, check exposure (are we vulnerable/exposed?), push blocks, write hunt for the behavior, brief owners."}, {"q": "IOCs vs TTPs for detection?", "a": "IOCs for fast blocking with expiry; TTPs for durable detections and hunts."}],
 "commands": ["# cert-transparency recon (needs net)\n# curl -s 'https://crt.sh/?q=%25.example.com&output=json' | head -c 500", "# quick reputation triage\n# check VirusTotal + AbuseIPDB links from OSINT tab"]},

"net-det": {
 "deep_dive": ["Signature detection (Snort/Suricata rules) catches known-bad fast with clear true-positives; behavioral NDR catches unknown-bad (beacons, odd hours, data spikes) with tuning cost. Beaconing math: humans browse bursty and varied; malware phones home at near-fixed intervals to one host with similar byte counts - look for low-jitter periodicity. DNS is the tell-tale: tunneling encodes data in long random labels with high query rates to attacker domains; also watch for brand-new domains (age < 30 days) in enterprise traffic and DNS over HTTPS bypassing local resolvers.",
  "Sensor placement decides everything: SPAN/taps at internet edge, datacenter uplinks, and between segments; full-packet capture on uplinks with short retention (days) plus Zeek-style logs long-term. TLS inspection is the eternal trade-off (visibility vs privacy/breakage) - many teams inspect only risky categories. Wireshark skill that pays: display filters (dns, http.request, tcp.port==4444), follow TCP stream, statistics -> protocol hierarchy to spot the odd one out."],
 "mistakes": ["IDS with default rules, never tuned (noise кладбище)", "No DNS logging (blind to tunneling/C2)", "Decrypting everything (breaks apps, angers legal)"],
 "interview": [{"q": "Hourly 500-byte POSTs to unknown IP. Read?", "a": "Suspected beaconing: check jitter, destination age/reputation, process owner, payload regularity; isolate if confirmed."}, {"q": "IDS vs IPS vs NDR?", "a": "IDS detects, IPS blocks inline, NDR baselines behavior for unknowns."}],
 "commands": ["# Wireshark essentials\ndns\nhttp.request\ntcp.port == 4444\nip.addr == 203.0.113.9", "# Suricata-style idea: alert on long DNS labels\n# dns.query.rrname; len > 60 + high rate"]},

"appsec": {
 "deep_dive": ["Injection happens when code and data share a channel: SQL queries built by string concat, OS commands with user input, even log lines (log injection). The universal fix is separation: parameterized queries/ORMs, allowlisted commands, encoded output. Broken access control (2021's #1) is subtler: the app checks login but not OWNERSHIP - changing /invoice/123 to /invoice/124 shows others' data (IDOR). Fix with server-side per-object checks on every endpoint, tested with two accounts. XSS splits three ways: reflected (link), stored (comment saved then shown to all - worst), DOM (client-side sink); output encoding by context + CSP headers cover all three.",
  "Shift-left that actually works: SAST in PRs (tuned, or developers ignore it), DAST against staging, SCA for dependencies with upgrade SLAs, plus security champions in each dev team translating findings into tickets developers accept. Threat model new features in 30 minutes (data flows, trust boundaries, abuse cases) - the cheapest bugs are the ones never written. Bug bounty last: invite the world only after basics are solid, scoped to crown jewels."],
 "mistakes": ["Client-side-only validation (attacker calls API directly)", "WAF as the only fix (band-aid over rotten code)", "Debug endpoints left in production"],
 "interview": [{"q": "IDOR example + fix?", "a": "/user/12 -> /user/13 shows others' data. Fix: server checks ownership on every object access; test with two accounts."}, {"q": "Stored vs reflected XSS?", "a": "Stored persists server-side hitting every viewer (worse); reflected needs a crafted link per victim."}],
 "commands": ["# quick header check\ncurl -sI https://target | grep -iE 'content-security-policy|x-frame|hsts'", "# classic SQLi probe (lab only, authorized)\n# ' OR '1'='1"]},

"cloud": {
 "deep_dive": ["Shared responsibility in one line: provider secures the CLOUD, you secure what's IN it - and nearly every breach is the second part. The fatal five: public storage buckets, 0.0.0.0/0 admin ports, root without MFA, no audit logging, secrets in code/repos. Guardrails beat reviews: SCPs that make public buckets impossible, IaC policies that reject open security groups at plan time, and CSPM scanning that screams within minutes of drift. Logging is the difference between 'we were breached' and 'we know exactly what was touched': CloudTrail/Activity Log on, centralized, alerted, retained.",
  "Identity is the control plane: short-lived roles over long-lived keys, SSO with phishing-resistant MFA, break-glass root sealed and alarmed. Network: private subnets by default, VPC endpoints instead of internet gateways where possible, egress filtering. Detection content for cloud looks different: impossible-travel logins, new access keys on root, disabled logging, mass snapshot sharing. Game day: practice the 'leaked key' drill until revocation takes minutes."],
 "mistakes": ["Root with password-only + old access keys", "Public buckets 'for testing' indexed forever", "CloudTrail off to 'save costs'"],
 "interview": [{"q": "Bucket with backups found public. First 3 steps?", "a": "Make private immediately, rotate any exposed secrets/keys, check access logs for who fetched what."}, {"q": "SCP vs security group?", "a": "SCP = guardrail limiting what accounts CAN do (even admins); SG = firewall on who reaches resources."}],
 "commands": ["# AWS: who can reach SSH? (needs aws cli)\n# aws ec2 describe-security-groups --query 'SecurityGroups[?IpPermissions[?ToPort==`22`]]'", "# find leaked keys in repo history\n# git log -p -S 'AKIA' --all | head -50"]},

"hardening": {
 "deep_dive": ["Every running service is a promise to defend: Telnet sends credentials in cleartext, SMBv1 carries wormable exploits, old TLS versions leak sessions. Hardening deletes promises you don't need, then locks the rest: firewall default-deny inbound (allow only documented ports), CIS benchmark baselines applied by automation (not memory), unique local-admin passwords (LAPS-style), and re-verification after every change because drift is constant - today's hardened gold image is next quarter's legacy.",
  "Measure it: benchmark pass percentage per fleet, count of unauthorized changes, mean time to remediate drift. Exceptions are fine (that one legacy app needs SMBv2) when they are written, owned, and expiring - undocumented exceptions are just vulnerabilities with extra steps. Pair hardening with monitoring: a hardened host that suddenly runs new services is itself an alert."],
 "mistakes": ["One-time hardening, never rechecked (drift wins)", "Exceptions by hallway conversation (no owner/expiry)", "Hardening production Friday evening"],
 "interview": [{"q": "Harden a fresh Windows server in 5 steps.", "a": "Patch fully; remove roles/features unused; firewall default-deny + needed ports; CIS baseline + unique local admin; enable logging/EDR then verify with scan."}, {"q": "Legacy app needs SMBv1. Call?", "a": "Document exception with owner + expiry, isolate host on its own segment, fund the migration, monitor it harder."}],
 "commands": ["# Windows roles you forgot about\nGet-WindowsFeature | Where Installed", "# Linux: what starts at boot?\nsystemctl list-unit-files --state=enabled | head -30"]},

"forensics": {
 "deep_dive": ["Volatility order rules everything: registers/cache, RAM, network state, running processes, disk, logs, archives. Kill power before RAM capture and keys, injected code, and C2 sessions vanish. Disk forensics reads layers: filesystem metadata (MFT times show mass-encryption bursts), OS artifacts (registry Run keys, Prefetch proving execution + count, Shimcache, event logs 4624/4625/4688), application traces (browser history = the phish click timestamp, downloads, mail stores). Memory forensics finds what disk cannot: process injection, rootkit hooks, in-memory-only payloads.",
  "Timelines turn piles into stories: merge filesystem + registry + browser + log timestamps (Plaso-style super-timelines), then read for cause-before-effect. Every claim needs two corroborating artifacts ('executed' = Prefetch + Shimcache, not one). Chain of custody (who touched evidence, when, with what tool, hash-verified copies) decides courtroom survival. Report structure that works: executive summary, timeline, findings per question asked, gaps, recommendations."],
 "mistakes": ["Power-off before RAM capture", "Analyzing originals instead of hashed copies", "Single-artifact conclusions"],
 "interview": [{"q": "Prove malware RAN, not just existed.", "a": "Prefetch (execution + count + last run) corroborated by Shimcache + 4688 process-creation logs."}, {"q": "Ransomware timeline from disk alone?", "a": "MFT mass-modify burst + ransom-note creation times + Run-key persistence + browser download of the lure, ordered."}],
 "commands": ["# MFT mass-modification hunt idea\n# fls -r -m / image.dd | grep -c '2024-'  # then timeline", "# Volatility-style triage (memory image)\n# python vol.py -f mem.raw windows.pslist"]},

"automation": {
 "deep_dive": ["Automation maturity climbs: level 1 enriches (hash -> VT link, IP -> geo/reputation, user -> manager) and drafts tickets; level 2 acts reversibly (disable phishing link, quarantine mail) with one-click approval; level 3 auto-contains proven-false-positive-free cases (isolate known-ransomware behavior) with instant rollback. Most teams should live at level 1-2: machine speed for gathering, human judgment for damage. Every playbook needs trigger conditions, step-by-step actions, rollback path, owner, and audit logging - unlogged automation is a liability factory.",
  "Build rules that survive: idempotent steps (re-runs are safe), secrets in vaults not code, rate limits on APIs, and dry-run modes. Test playbooks in staging against replayed alerts; measure analyst-minutes saved versus maintenance cost, and retire playbooks whose FP rate exceeds their value. This very tool demonstrates the pattern: detectors (automation) + risk score (prioritization) + email (notification) + human review (you)."],
 "mistakes": ["Auto-blocking with unknown FP rate (self-inflicted outage)", "Secrets hardcoded in playbooks", "No rollback path on destructive steps"],
 "interview": [{"q": "Playbook for phishing URL reports?", "a": "Trigger: user report; enrich (reputation, detonated screenshot); auto-quarantine similar mails; approval-gated domain block; ticket with timeline."}, {"q": "Automation ROI measure?", "a": "Analyst-minutes saved + MTTR drop, minus maintenance hours and FP incidents caused."}],
 "commands": ["import hashlib\nsha = hashlib.sha256(open('evil.apk','rb').read()).hexdigest()\nprint(f'https://www.virustotal.com/gui/search/{sha}')", "# SOAR-style approval gate (pseudo)\n# if verdict == 'malicious' and confidence > 0.95: isolate(host)  # else: ticket()"]},

"frameworks": {
 "deep_dive": ["Use each map for its question. ATT&CK: HOW do they act - tactics (why: initial access) down to techniques (T1110 brute-force) and procedures (the exact command seen). Build detections per technique and heatmap coverage; red cells are your backlog. NIST CSF 2.0: is the PROGRAM complete - Govern (strategy, risk appetite), Identify, Protect, Detect, Respond, Recover; score each function 1-4 and fund the lowest first. CIS Controls v8: WHAT first - IG1 (inventory, patching, MFA, backups) is the small-team survival kit. Kill Chain: WHERE to break in - seven stages from recon to actions; one solid break (killing delivery OR C2) defeats the whole chain.",
  "D3FEND closes the loop: for each ATT&CK technique it lists engineered countermeasures (e.g. credential hardening vs T1110), turning 'we lack coverage' into shopping lists. NIST SP 800-61 gives the 6-phase response rhythm used in Room 8. Present frameworks to leadership as coverage math, not posters: technique coverage %, CSF maturity trend, CIS IG1 pass rate. Reassess yearly or after every major incident."],
 "mistakes": ["ATT&CK poster with zero mapped detections", "CSF self-scores with no evidence", "Buying tools before IG1 basics"],
 "interview": [{"q": "Show ATT&CK-driven defense for T1566.", "a": "Detections: gateway verdicts + click telemetry; mitigations: DMARC reject, sandboxing, MFA; test with simulated phish; measure report rate."}, {"q": "CSF Govern vs old Identify?", "a": "Govern (new in 2.0) owns strategy/roles/risk appetite above the operational five - leadership accountability, not just asset lists."}],
 "commands": ["# coverage self-check (pseudo)\n# for t in [T1110, T1190, T1566, T1486]: print(t, has_tested_rule(t))", "# CIS IG1 spot-check\n# inventory? patching SLA? MFA admins? backups tested?"]},
}
