"""Leveled coaching: every level 500+ chars with its own diagram spec. ASCII only."""

LEVELS = {
"sec-fund": {
 "beginner": "WHAT: The CIA Triad is three promises every security effort makes. Confidentiality means only the right people can read something — like a sealed exam paper that only the examiner opens. Integrity means nobody secretly changed it — like tamper-proof seals on medicine bottles. Availability means it works when you need it — like the school being open on exam day. WHY it matters: every single cyber attack breaks at least one promise. A leaked customer list breaks confidentiality. A ransomware lockdown breaks availability. A silently altered bank balance breaks integrity. Learn to name which promise each incident breaks and you already think like an analyst.",
 "img_b": {"kind": "triangle", "title": "CIA Triad: which promise breaks?", "levels": [{"label": "CONFIDENTIALITY", "sub": "leaks, snooping, exposed DBs"}, {"label": "INTEGRITY", "sub": " altered data, fake updates"}, {"label": "AVAILABILITY", "sub": "ransomware, DDoS, outages"}]},
 "intermediate": "HOW it works daily: AAA enforces the triad. Authentication proves WHO you are — password plus a second proof (MFA). Authorization decides WHAT you may touch — students read, teachers edit, admins configure. Accounting writes it all down — who did what, when — so incidents can be reconstructed. These stack into defense-in-depth: a firewall blocks the network knock, MFA stops the stolen password, EDR catches the running payload, backups undo the encryption. One layer fails; all layers at once rarely do. Walk through any alert and ask: which layer failed, and which layer caught it?",
 "img_i": {"kind": "pipeline", "title": "AAA on every login", "steps": ["Authenticate: password + MFA", "Authorize: role decides access", "Accounting: log everything"]},
 "advanced": "Enterprise nuance: controls split into preventive (MFA, firewall rules — they stop), detective (SIEM alerts, audits — they spot), and corrective (backups, key rotation — they restore). Mature teams map coverage per ATT&CK technique: T1110 brute-force should have preventive lockout AND detective alerting AND corrective reset playbooks. Residual risk gets formally accepted in writing, never silently. The economic art: maximum risk reduction per unit of user friction — a control users bypass (passwords on sticky notes) is negative security. Audit tip: take each HIGH finding in Analyze and name its missing control type.",
 "img_a": {"kind": "stack", "title": "Control stack around every asset", "rows": [{"label": "Preventive: MFA, firewall, allowlists", "sub": "stop the attempt"}, {"label": "Detective: SIEM, EDR, audits", "sub": "spot what passed"}, {"label": "Corrective: backups, rotation", "sub": "restore and recover"}]},
 "diagram": {"kind": "rings", "title": "Defense rings around CIA", "rings": [{"label": "CIA core"}, {"label": "Policy + training"}, {"label": "Technical controls"}, {"label": "Monitoring + response"}]}},

"net-sec": {
 "beginner": "WHAT: Computers talk through numbered doors called ports, using shared languages called protocols. Port 443 with HTTPS is the encrypted web — the padlock in your browser. Port 22 is SSH remote administration; 3389 is Windows RDP; 445 is file sharing. WHY it matters: attackers automatically knock on every door of every internet address. An open RDP door lets criminals guess passwords all day, and RDP break-ins are a top ransomware starter. Close doors you don't need and most automated attacks simply bounce off.",
 "img_b": {"kind": "stack", "title": "Doors on a typical server", "rows": [{"label": "443 HTTPS: open, encrypted web", "sub": "needed, keep + patch"}, {"label": "22 SSH: admin only via VPN", "sub": "never public"}, {"label": "3389 RDP / 445 SMB: internal only", "sub": "top ransomware vectors"}]},
 "intermediate": "HOW the pieces fit: TCP/IP delivers packets with a handshake (SYN, SYN-ACK, ACK); DNS translates names to IPs and attackers poison or mimic it; firewalls allow or deny by port and address; VPNs encrypt remote access so admins never log in over open internet; proxies filter and log web traffic. Segmentation splits the network into zones — users, servers, guests — so one breached laptop cannot stroll into the database. Our brute-force lab is exactly this: watching SSH port-22 guessing arrive from the wild.",
 "img_i": {"kind": "pipeline", "title": "Packet's journey through defenses", "steps": ["Internet knock", "Firewall: port allowed?", "WAF: payload clean?", "Server: patched + logged"]},
 "advanced": "Enterprise nuance: default-deny EGRESS (servers may call out only to approved places) quietly kills most command-and-control; DNS query logging catches tunneling and look-alike domains; micro-segmentation plus zero-trust removes the idea that 'inside = safe'. Every firewall exception needs a documented business owner and quarterly review, or rules fossilize into holes. Measure: internet-exposed critical ports trending to zero, mean time to close an unauthorized opening, and DNS tunnels caught per quarter.",
 "img_a": {"kind": "arch", "title": "Zero-trust path (verify everywhere)", "boxes": [{"label": "Any request", "sub": "inside or outside"}, {"label": "Identity + device check", "sub": "MFA, posture, risk"}, {"label": "Least-privilege access", "sub": "this app, this hour"}]},
 "diagram": {"kind": "topology", "title": "Network zones under fire", "nodes": [
   {"label": "Internet", "zone": "hostile"},
   {"label": "Firewall", "zone": "filters"},
   {"label": "DMZ web", "zone": "isolated"},
   {"label": "DB LAN", "zone": "private"}]}},

"endpoint": {
 "beginner": "WHAT: Endpoints — laptops, desktops, servers — are where attackers land and run code. Antivirus is a guard matching known criminals by photo (signatures); EDR is a detective watching BEHAVIOR (why is Word launching PowerShell at midnight?). WHY it matters: nearly every attack executes on an endpoint, so a blind endpoint means invisible attacks. Patching closes holes criminals already know: most exploited bugs have fixes available, and attackers count on you skipping them.",
 "img_b": {"kind": "pipeline", "title": "How an attack lands", "steps": ["Phish click", "Payload runs", "Guard? Detective?", "Patch would have blocked"]},
 "intermediate": "HOW to defend in practice: harden first — remove what attackers use (SMBv1, Telnet, unused apps); patch on a schedule with KEV-listed exploited bugs jumping the queue; do daily work as a NON-admin so malware inherits no crown; keep the host firewall on; maintain offline, TESTED backups (an untested backup is a hope, not a plan). EDR telemetry — process trees, command lines, network flows — doubles as your richest forensic source; retain 30-90 days hot.",
 "img_i": {"kind": "stack", "title": "Patch priority order", "rows": [{"label": "1st: KEV + internet-facing", "sub": "exploited now, days"}, {"label": "2nd: CVSS high", "sub": "this cycle"}, {"label": "3rd: everything else", "sub": "scheduled windows"}]},
 "advanced": "Enterprise nuance: application allowlisting on servers (nothing runs unless approved — brutal to operate, devastating to attackers), USB/removable-media control, unique local-admin passwords per host, CIS benchmarks enforced by configuration management, and patch rings (pilot group, then fleet). Track mean time to patch KEV plus EDR coverage percentage; review weekly. Trade-off to manage openly: aggressive hardening breaks legacy apps, so pilot, document exemptions with owners and expiry dates.",
 "img_a": {"kind": "arch", "title": "Mature endpoint program", "boxes": [{"label": "Baseline: CIS gold image", "sub": "built, versioned"}, {"label": "Enforce: config mgmt", "sub": "drift auto-fixed"}, {"label": "Watch: EDR + coverage %", "sub": "blind spots named"}, {"label": "Recover: tested backups", "sub": "restore drilled"}]},
 "diagram": {"kind": "meters", "title": "Endpoint health dashboard", "meters": [
   {"label": "Patched (KEV done)", "pct": 92},
   {"label": "EDR coverage", "pct": 87},
   {"label": "Backups tested", "pct": 60},
   {"label": "Admin hygiene", "pct": 74}]}},

"iam": {
 "beginner": "WHAT: IAM makes sure the right people — and only them — reach the right things. Login proves WHO you are (authentication); permissions decide WHAT you may do (authorization). MFA demands two DIFFERENT proofs, like password plus phone code, so a stolen password alone fails. WHY it matters: stolen logins cause most breaches, and password-only accounts fall to the exact guessing our brute-force lab demonstrates.",
 "img_b": {"kind": "pipeline", "title": "Why MFA wins", "steps": ["Attacker steals password", "Real site asks 2nd proof", "No phone = no entry"]},
 "intermediate": "HOW teams run it: SSO gives one strong login for many apps instead of twenty weak ones (guard that one login fiercely); RBAC bundles permissions by job role with quarterly reviews removing drift; privileged admin accounts stay separate, vaulted, and time-bound; joiner-mover-leaver automation removes stale access the day people move. Authenticator apps and passkeys resist phishing far better than SMS codes, which fall to SIM-swap and interception.",
 "img_i": {"kind": "stack", "title": "MFA strength ladder", "rows": [{"label": "Strongest: passkey / hardware key", "sub": "phishing-resistant"}, {"label": "Strong: authenticator app", "sub": "time-based codes"}, {"label": "Weak: SMS codes", "sub": "SIM-swappable"}]},
 "advanced": "Enterprise nuance: Privileged Access Management with just-in-time elevation and recorded sessions; conditional access weighing device posture, location, and risk signals (unknown device plus new country equals step-up or block); sealed break-glass accounts for IdP outages, monitored and tested yearly. Metrics that matter: 100% MFA on admins, 100% of privileged sessions through PAM, stale-account count trending to zero.",
 "img_a": {"kind": "arch", "title": "Privileged access flow", "boxes": [{"label": "Request with reason", "sub": "ticketed, time-bound"}, {"label": "Approve + MFA", "sub": "manager or auto-policy"}, {"label": "Vaulted session", "sub": "recorded, expiring"}]},
 "diagram": {"kind": "flowchart", "title": "Access decision tree", "steps": [
   {"q": "MFA passed?", "yes": "continue", "no": "block + alert"},
   {"q": "Role allows resource?", "yes": "continue", "no": "deny + log"},
   {"q": "Device + context clean?", "yes": "allow, logged", "no": "step-up auth"}]}},

"monitoring": {
 "beginner": "WHAT: Logs are diaries computers keep — who logged in, which page was requested, which domains were asked about. Attackers cannot act without writing in these diaries: guessing leaves failed logins, break-ins leave odd-hour successes, web probes leave strange URLs. WHY it matters: reading diaries is how small teams catch big attacks; every detector in this tool is simply one diary-reading rule.",
 "img_b": {"kind": "pipeline", "title": "One attack, four diary entries", "steps": ["Fails x50: auth log", "3 AM success: event log", "Odd URL: web log", "Strange domain: DNS log"]},
 "intermediate": "HOW to do it well: collect auth logs (Linux auth.log, Windows events 4625 failed / 4624 success), web access logs, DNS and firewall logs into ONE place with clocks synced by NTP (a five-minute skew scrambles multi-host timelines). Write behavior rules first — '6 fails from one IP' — then tune thresholds from YOUR baseline: too low drowns you in noise, too high sleeps through attacks. Also alert on ABSENCE: a domain controller gone silent may mean logging was killed.",
 "img_i": {"kind": "stack", "title": "Log pipeline", "rows": [{"label": "Collect centrally", "sub": "forwarders, NTP-synced"}, {"label": "Parse fields", "sub": "IP, user, action"}, {"label": "Rule + threshold", "sub": "tuned to baseline"}]},
 "advanced": "Enterprise nuance: retention tiers (90 days hot for hunting, a year cold for forensics), per-asset baselines so anomalies stand out, rule lifecycle with precision tracking (true-positive rate per rule), and coverage mapping against ATT&CK techniques to find blind techniques. Metrics: log-source coverage percentage and mean time to detect. Review rules quarterly; retire or fix anything under your precision bar.",
 "img_a": {"kind": "arch", "title": "Mature monitoring program", "boxes": [{"label": "Coverage: sources mapped", "sub": "knows blind spots"}, {"label": "Rules: tested + tuned", "sub": "precision tracked"}, {"label": "Review: quarterly cycle", "sub": "retire or repair"}]},
 "diagram": {"kind": "logstream", "title": "Midnight in the logs (find evil)", "lines": [
   {"t": "02:11 Accepted password for alice from 10.0.0.4"},
   {"t": "02:12 Failed password for root from 203.0.113.9", "evil": True},
   {"t": "02:12 Failed password for admin from 203.0.113.9", "evil": True},
   {"t": "02:13 Failed password for admin from 203.0.113.9", "evil": True},
   {"t": "02:14 Backup job completed on db-01"}]}},

"siem": {
 "beginner": "WHAT: A SIEM (Splunk, Microsoft Sentinel, QRadar) is a giant log library with a very smart librarian. It gathers logs from every system and shouts when combined patterns match attacks — failed logons PLUS an odd-country success equals one account-takeover incident, not two random alerts. WHY it matters: humans cannot read millions of lines; correlation turns noise into the one alert worth waking up for.",
 "img_b": {"kind": "pipeline", "title": "Noise in, incident out", "steps": ["50 failed logins", "+ 3 AM new-country success", "= 1 account-takeover alert"]},
 "intermediate": "HOW it works: agents forward logs (ingestion), fields get normalized so one query spans vendors, correlation rules encode attacker behavior, dashboards show posture at a glance, and analysts hunt with query languages — SPL in Splunk, KQL in Sentinel. Tune like our threshold slider: lower catches more but cries wolf; higher sleeps quietly. Every rule needs an owner, a runbook, and a precision target.",
 "img_i": {"kind": "stack", "title": "Rule lifecycle", "rows": [{"label": "Draft from technique", "sub": "ATT&CK-mapped"}, {"label": "Test on 30d history", "sub": "measure precision"}, {"label": "Alert-only pilot", "sub": "watch FP rate"}, {"label": "Enforce + runbook", "sub": "analysts act"}]},
 "advanced": "Enterprise nuance: content-as-code (rules in git, reviewed, tested like software), cost control per gigabyte ingested (full fidelity for auth/EDR/DNS, sampled debug chatter — with drop-rules documented), and use-case coverage heatmaps against ATT&CK. Track true-positive rate per rule and technique coverage, not raw alert counts. This tool mirrors the whole loop at pocket scale: ingest samples, detect with rules, score risk, alert by mail.",
 "img_a": {"kind": "arch", "title": "SIEM maturity ladder", "boxes": [{"label": "Collect: all sources in", "sub": "coverage %"}, {"label": "Detect: tested rules", "sub": "precision tracked"}, {"label": "Hunt: proactive queries", "sub": "heat-mapped"}]},
 "diagram": {"kind": "funnel", "title": "SIEM: noise in, incidents out", "stages": [
   {"label": "Events collected", "n": "2M/day"},
   {"label": "Rule matches", "n": "1,200"},
   {"label": "Triaged alerts", "n": "40"},
   {"label": "Real incidents", "n": "3"}]}},

"soc-ops": {
 "beginner": "WHAT: A SOC is the hospital emergency room for cyber attacks, and L1 analysts are the triage nurses. Every alert gets the same questions: real emergency or false alarm? How bad, how wide, how fast must we move? WHY it matters: speed plus good notes decides whether a breach stays one laptop or becomes company-wide. The next analyst continues from your ticket — write it like they'll read it at 3 AM.",
 "img_b": {"kind": "pipeline", "title": "Triage nurse flow", "steps": ["Alert arrives", "Real or false alarm?", "Treat small / send big up"]},
 "intermediate": "HOW to triage: validate with evidence first (true vs false positive — gut second), scope the blast radius (one host or a subnet? one account or fifty?), separate severity (damage done) from priority (response order — active ransomware outranks dormant adware), then contain small issues yourself or escalate with timeline plus evidence attached. Document everything: IOCs, actions with timestamps, and reasoning including why FPs were closed.",
 "img_i": {"kind": "stack", "title": "Escalation packet", "rows": [{"label": "Alert + raw evidence", "sub": "logs, screenshots"}, {"label": "What you checked", "sub": "queries run, results"}, {"label": "Hypothesis + need", "sub": "what L2 should do"}]},
 "advanced": "Enterprise nuance: SLAs per severity with on-call rotations, shift-handover discipline (medical-chart quality), per-alert-type runbooks, and a false-positive feedback loop back to rule owners so noise shrinks monthly. Watch the human metrics too: mean time to acknowledge and respond, escalation acceptance rate (are your escalations good?), and burnout signals — tuning noisy rules beats heroically clicking through them.",
 "img_a": {"kind": "arch", "title": "SOC metrics that matter", "boxes": [{"label": "MTTA / MTTR", "sub": "speed, trending down"}, {"label": "FP rate per rule", "sub": "noise, trending down"}, {"label": "Escalation quality", "sub": "accepted, not bounced"}]},
 "diagram": {"kind": "kanban", "title": "SOC triage board", "cols": [
   {"label": "New", "cards": ["Odd login 3 AM", "Weird URL click"]},
   {"label": "Triaging", "cards": ["50 fails + success"]},
   {"label": "Escalated", "cards": ["Ransomware behavior"]},
   {"label": "Closed", "cards": ["Scanner noise (FP)"]}]}},

"ir": {
 "beginner": "WHAT: Incident Response is the fire-drill plan for breaches: who does what, in which order, with what authority. Without it people panic, delete evidence, and let attackers stroll back in. WHY it matters: six ordered phases turn chaos into a repeatable rescue — and skipping phases is how 'fixed' incidents resurrect. Think of it like emergency medicine: triage, stabilize, operate, rehab, prevention — in that order, every time.",
 "img_b": {"kind": "pipeline", "title": "Order saves you", "steps": ["Isolate first", "Remove evil", "Then recover"]},
 "intermediate": "HOW per NIST SP 800-61: PREPARE before anything (playbooks, contact lists, backups, war-room criteria); DETECT and ANALYZE (confirm it's real, scope it); CONTAIN (pull the network cable — not the power, if memory capture matters — block bad IPs); ERADICATE (kill persistence, close the hole); RECOVER (restore from clean sources, watch closely); LESSONS-LEARNED (fix root causes with funded owners). Recovering before eradicating guarantees reinfection — the classic failure.",
 "img_i": {"kind": "stack", "title": "Containment options", "rows": [{"label": "Host isolate (EDR)", "sub": "fastest, keeps memory"}, {"label": "Network block IOCs", "sub": "firewall, mail, DNS"}, {"label": "Credential reset", "sub": "kill sessions first"}]},
 "advanced": "Enterprise nuance: severity classification with war-room triggers (ransomware behavior, exfil indicators, multi-host, customer data); legal, HR, and comms in the loop early; chain-of-custody evidence handling with write-blockers; tabletop exercises twice yearly rehearsing decisions like 'who may halt production'; an external IR retainer for the big ones. Measure time-per-phase and repeat-incident rate — the second must fall.",
 "img_a": {"kind": "arch", "title": "War-room readiness", "boxes": [{"label": "Playbooks + contacts", "sub": "tested, current"}, {"label": "Authority pre-approved", "sub": "who can halt prod"}, {"label": "Comms + legal looped", "sub": "one spokesperson"}]},
 "diagram": {"kind": "wheel", "title": "IR cycle", "steps": ["Prepare", "Detect + Analyze", "Contain", "Eradicate", "Recover", "Lessons learned"]}},

"threat-det": {
 "beginner": "WHAT: Detections are traps. A weak trap uses the criminal's photo (a file hash — changed in an hour). A strong trap watches BEHAVIOR (password guessing at 3 AM — forcing a whole new method to evade). WHY it matters: behavior traps keep catching attackers for years while hash lists rot daily. Hunt proactively with ideas ('if ransomware is here, shadow copies die first') instead of waiting for alerts.",
 "img_b": {"kind": "triangle", "title": "Trap strength", "levels": [{"label": "Photo traps: hashes, IPs", "sub": "rot in hours"}, {"label": "Habit traps: tools, artifacts", "sub": "last weeks"}, {"label": "Behavior traps: TTPs", "sub": "last years"}]},
 "intermediate": "HOW the layers stack: IOCs (IPs, hashes, domains) block fast but expire fast — always stamp expiry dates. IOAs catch behavior artifacts ('encoded PowerShell launched from Word'). TTPs (ATT&CK techniques like T1110 brute-force) detect whole methods durably. The Pyramid of Pain ranks them by what changing costs the attacker. Confirm wins by encoding them as tested rules so the next identical attack fires automatically.",
 "img_i": {"kind": "stack", "title": "From alert to durable rule", "rows": [{"label": "Catch: IOC blocks now", "sub": "IP, hash, domain"}, {"label": "Learn: extract behavior", "sub": "what did it DO?"}, {"label": "Encode: TTP rule + test", "sub": "catches next variant"}]},
 "advanced": "Enterprise nuance: detection-as-code with atomic tests that fire each rule on demand (unit tests for security); ATT&CK coverage heatmaps showing blind techniques worked by risk order; behavioral baselines per population (admins travel — service accounts must not); FP budgets per rule. Feed every confirmed detection back into blocks, rules, and hunts. Metric: technique coverage plus detection-to-triage time.",
 "img_a": {"kind": "arch", "title": "Detection program", "boxes": [{"label": "Map: techniques vs stack", "sub": "heat-mapped gaps"}, {"label": "Build: tested rules", "sub": "as code, in git"}, {"label": "Hunt: hypothesis sprints", "sub": "encode the wins"}]},
 "diagram": {"kind": "triangle", "title": "Pyramid of Pain (higher = hurts attackers more)", "levels": [
   {"label": "Hashes / IPs", "sub": "trivial to change"},
   {"label": "Domains / artifacts", "sub": "annoying to change"},
   {"label": "Tools + TTPs", "sub": "forces attacker retooling"}]}},

"malware": {
 "beginner": "WHAT: Malware is hostile software in costumes. Ransomware locks your files and demands crypto. Trojans pose as legit apps with hidden backdoors. Worms spread alone across networks. Spyware watches quietly and steals. WHY it matters: one careless click or one unpatched hole is enough — but offline tested backups plus refusing unknown files defeats nearly all of it. Never pay: decryption often fails and payment marks you for repeats.",
 "img_b": {"kind": "pipeline", "title": "Spot the costume", "steps": ["invoice.pdf.exe = trojan", "Ransom note = ransomware", "Slow PC + odd traffic = spyware"]},
 "intermediate": "HOW infections flow: delivery (phishing mail, shady download), execution (the double-click — the chokepoint to guard with allowlisting and macro policies), persistence (auto-start Run keys, scheduled tasks, services), then call-home to criminal servers or mass encryption. Two great tripwires: ransomware deletes shadow copies (vssadmin) and renames thousands of files — either alone is a high-fidelity alert. Sandbox unknowns: detonate attachments in isolation and watch 5 minutes.",
 "img_i": {"kind": "stack", "title": "Kill it at chokepoints", "rows": [{"label": "Delivery: filter + sandbox", "sub": "mail, web"}, {"label": "Execution: allowlist + EDR", "sub": "the moment of truth"}, {"label": "Persistence: Run keys watched", "sub": " autostart audit"}]},
 "advanced": "Enterprise nuance: email-attachment sandbox detonation with verdict SLAs, egress filtering (workstations reach only approved outside ports), honeypots and canary files for early warning, and a rehearsed ransomware playbook covering comms, legal, and rebuild order. Measure backup-restore success rate and host-isolation time, not just infections blocked. Assume breach drills should include a full simulated encryption weekend yearly.",
 "img_a": {"kind": "arch", "title": "Ransomware readiness", "boxes": [{"label": "Prevent: patch + filter", "sub": "shrink entry"}, {"label": "Detect: EDR + canaries", "sub": "minutes matter"}, {"label": "Recover: offline backups", "sub": "drilled restores"}]},
 "diagram": {"kind": "branches", "title": "One lure, many payloads", "root": "invoice.pdf.exe arrives", "arms": [
   {"label": "Trojan", "sub": "backdoor opens"},
   {"label": "Ransomware", "sub": "files encrypted"},
   {"label": "Spyware", "sub": "keys logged"}]}},

"phish-email": {
 "beginner": "WHAT: Phishing is lying to steal — a fake bank mail rushes you to a fake login page, and typed passwords go straight to criminals. Spear-phishing researches YOU personally; whaling targets bosses. WHY it matters: it is the number-one break-in method, cheaper than hacking and effective against anyone in a hurry. The defense mindset: verify through a DIFFERENT channel, never the one shouting.",
 "img_b": {"kind": "pipeline", "title": "Anatomy of a phish", "steps": ["Authority + urgency", "Fake link", "Stolen password"]},
 "intermediate": "HOW to dissect any mail in 30 seconds: compare From against Reply-To and Return-Path; hover every link and read the REAL domain (look-alikes, bare IPs, free TLDs); treat urgency plus threats as a lure signature; quarantine unexpected attachments and never enable their macros. Technical armor: SPF declares allowed senders, DKIM signs mail cryptographically, DMARC enforces alignment with quarantine-then-reject policy. Report buttons turn each user into a sensor improving filters for all.",
 "img_i": {"kind": "stack", "title": "Email defense layers", "rows": [{"label": "SPF/DKIM/DMARC", "sub": "prove senders"}, {"label": "Gateway sandbox", "sub": "detonate payloads"}, {"label": "MFA + manager", "sub": "stolen passwords fail"}]},
 "advanced": "Enterprise nuance: DMARC rollout path (p=none with aggregate reports, fix marketing and SaaS senders, then quarantine, then reject); display-name spoof rules for executives; attachment sandboxing plus safe-link rewriting; risk-based simulations for finance, HR, and execs measuring REPORT rate, not just clicks; and a payment-change process requiring voice callbacks to known numbers plus dual approval — the only real BEC defense.",
 "img_a": {"kind": "arch", "title": "Anti-BEC process", "boxes": [{"label": "Payment request arrives", "sub": "any channel"}, {"label": "Callback known number", "sub": "never reply-path"}, {"label": "Dual approval", "sub": "no exceptions"}]},
 "diagram": {"kind": "emailmock", "title": "Dissect this mail", "lines": [
   {"t": "From: IT-Desk <it-desk@gmail.com> (claims to be your company)"},
   {"t": "Subject: Mailbox FULL — verify in 24h or LOSE access", "flag": True, "why": "urgency + threat"},
   {"t": "Click: http://192.0.2.9.verify-login.tk/inbox", "flag": True, "why": "bare IP + look-alike domain"},
   {"t": "Reply-To: helpdesk-random@outlook.com", "flag": True, "why": "identity mismatch"},
   {"t": "Best regards, IT Department"}]}},

"vuln-mgmt": {
 "beginner": "WHAT: Software has holes; each public one gets a name (CVE-2024-1234) and a danger score 0-10 (CVSS). Patching closes them. WHY it matters: attackers scan the whole internet for unpatched systems within HOURS of disclosure — running old software is standing in the rain hoping. A special list, CISA KEV, names bugs criminals actively use: those jump every queue.",
 "img_b": {"kind": "stack", "title": "Name, score, action", "rows": [{"label": "CVE: the name", "sub": "CVE-2024-1234"}, {"label": "CVSS: the score 0-10", "sub": "how bad in theory"}, {"label": "KEV: exploited NOW?", "sub": "patch regardless"}]},
 "intermediate": "HOW the program runs: inventory everything (you cannot patch what you cannot list); scan WITH credentials for truth (Nessus/OpenVAS see missing patches and bad configs, outside scans see only the surface); rank by CVSS plus KEV status plus internet exposure plus asset value; fix by patching (remediation) or workaround (mitigation — do both, in that order); rescan to actually close tickets. CVSS itself blends exploitability (network? clicks? privileges?) with impact and scope (does it jump systems, like container escapes?).",
 "img_i": {"kind": "pipeline", "title": "Patch loop", "steps": ["Inventory assets", "Scan authenticated", "Rank: CVSS+KEV+exposure", "Fix then rescan"]},
 "advanced": "Enterprise nuance: risk-based SLAs (KEV internet-facing in days, highs in-cycle), an exception register with EXPIRY (risk acceptance, not ignorance), coordinated-disclosure handling, SBOMs exposing which apps hide which libraries (Log4j taught everyone), and vuln data piped into ticketing with named owners. Report trends — mean age of criticals, percent KEV inside SLA — never raw counts. Celebrate closed loops, not scan volumes.",
 "img_a": {"kind": "arch", "title": "Vuln program health", "boxes": [{"label": "Know: full inventory", "sub": "SBOM included"}, {"label": "Prioritize: risk, not score", "sub": "KEV + exposure"}, {"label": "Close: verified fixes", "sub": "SLA-tracked"}]},
 "diagram": {"kind": "heatmap", "title": "What to patch first? (exposure x severity)", "rows": ["Internet-facing", "Internal"], "cols": ["CVSS low", "CVSS high", "On KEV"], "cells": {("Internet-facing", "CVSS low"): 1, ("Internet-facing", "CVSS high"): 2, ("Internet-facing", "On KEV"): 3, ("Internal", "CVSS low"): 0, ("Internal", "CVSS high"): 1, ("Internal", "On KEV"): 2}}},

"ti": {
 "beginner": "WHAT: Threat Intelligence is knowing your enemy — WHO attacks (gangs, spies, insiders), HOW (their tricks, called TTPs), and WHAT to block first. WHY it matters: defending blind means patching everything equally; intel points at what is actually coming for organizations like yours, so effort lands where attacks will. A hospital and a bank face different enemies — intel tells each which doors to bar first, instead of barricading everything equally.",
 "img_b": {"kind": "pipeline", "title": "Intel answers three questions", "steps": ["WHO is coming?", "HOW do they act?", "WHAT do we block?"]},
 "intermediate": "HOW to work it: consume feeds (CISA KEV for exploited bugs, abuse.ch IOCs), map adversary methods to ATT&CK techniques, push blocks and write detections, share with peers. Prefer TTPs over raw IPs and hashes — atoms rot in days, methods persist for years. Our OSINT tab is a mini TI workbench: DNS history, certificate transparency, and reputation lookups you can run today. Always stamp confidence and expiry on intel; auto-blocking stale IOCs causes self-inflicted outages.",
 "img_i": {"kind": "stack", "title": "Intel value stack", "rows": [{"label": "TTPs (methods)", "sub": "durable, hunt them"}, {"label": "Tools + artifacts", "sub": "medium life"}, {"label": "IPs + hashes", "sub": "block fast, expire fast"}]},
 "advanced": "Enterprise nuance: start from leadership's intel requirements (what keeps execs up?), run a TIP platform with confidence scoring and auto-expiry, launch intel-driven hunting sprints per sector threat, share through ISACs and peer groups, and measure outcomes — campaigns blocked pre-impact, detection lead-time gained — not IOC volume. Publish a one-page weekly brief (actors, relevant TTPs, actions taken); it beats a 5000-row dump nobody reads.",
 "img_a": {"kind": "arch", "title": "Intel that lands", "boxes": [{"label": "Require: exec fears", "sub": "directed collection"}, {"label": "Produce: briefs + rules", "sub": "not raw dumps"}, {"label": "Measure: outcomes", "sub": "blocked, faster"}]},
 "diagram": {"kind": "merge", "title": "Many feeds, one decision", "ins": ["CISA KEV", "abuse.ch IOCs", "OSINT tab", "Peer ISAC"], "out": "Block + detect + hunt"}},

"net-det": {
 "beginner": "WHAT: When endpoints lie — or lack agents — the network still tells truth. IDS boxes watch traffic and shout at known-bad patterns; IPS versions also block inline. WHY it matters: command-and-control beacons, data theft uploads, and worm spread all cross the wire, visible to anyone watching flows and packets. An endpoint can lie or go dark; the wire rarely does.",
 "img_b": {"kind": "pipeline", "title": "What the wire reveals", "steps": ["Regular beacons = C2", "Huge uploads = theft", "One host, many ports = scan"]},
 "intermediate": "HOW detection splits: signatures catch known-bad fast with clear verdicts; behavioral baselines (NDR) catch the unknown — odd-hours activity, beacon regularity, data-volume spikes. DNS is gold: tunneling hides stolen data in long random subdomain labels with heavy query rates; also flag look-alike and day-old domains. Wireshark filters that pay rent: dns, http.request, tcp.port==4444, ip.addr == suspect, then Follow TCP Stream. Place sensors where traffic concentrates: internet edge, datacenter uplinks, between segments.",
 "img_i": {"kind": "stack", "title": "Traffic evidence ladder", "rows": [{"label": "Flow records", "sub": "who talked, how much"}, {"label": "Zeek logs", "sub": "protocols decoded"}, {"label": "Full packets (short)", "sub": "absolute truth, brief"}]},
 "advanced": "Enterprise nuance: TLS-inspection trade-offs (visibility versus privacy and breakage — many inspect only risky categories), full-capture on uplinks with days-long retention plus long-lived Zeek logs, encrypted-DNS (DoH) strategy so visibility doesn't silently vanish, per-segment NDR tuning, and pcap-backed alert context for analysts. Measure malicious-connection catch rate and triage time, not sensor counts.",
 "img_a": {"kind": "arch", "title": "Detection-in-depth on wire", "boxes": [{"label": "Signature: known-bad", "sub": "fast, precise"}, {"label": "Behavior: unknown-bad", "sub": "tuned baselines"}, {"label": "Forensic: packets", "sub": "prove it"}]},
 "diagram": {"kind": "packet", "title": "Read the packet: what is evil?", "fields": [
   {"label": "Eth: cc:46:d6:aa:bb:cc", "sub": "local hardware"},
   {"label": "IP: 10.0.0.5 -> 203.0.113.9", "sub": "unknown outside host"},
   {"label": "TCP: :443 -> :4444", "sub": "odd destination port", "evil": True},
   {"label": "DNS: a91x7z2q.tk, len 64, every 60s", "sub": "tunneling pattern", "evil": True}]}},

"appsec": {
 "beginner": "WHAT: Apps are the front door — login forms, search boxes, uploads. Attackers type tricks into them: SQL injection steals databases, XSS hijacks visitors' browsers, and one guessed URL (/invoice/124) reads someone else's data. WHY it matters: most breaches begin at an app input nobody validated. The mindset: never trust the browser; every input is hostile until proven otherwise.",
 "img_b": {"kind": "pipeline", "title": "One input, three disasters", "steps": ["' OR '1'='1 = data stolen", "<script> = visitors hijacked", "/124 = others' invoices"]},
 "intermediate": "HOW the OWASP Top 10 breaks down: injection dies to parameterized queries and ORMs (separate code from data); broken access control — 2021's number one — dies to deny-by-default plus server-side per-object checks tested with two accounts; XSS (reflected per-link, stored hitting every viewer, DOM client-side) dies to context-correct output encoding plus Content-Security-Policy; misconfiguration dies to hardened baselines with no debug endpoints; vulnerable components die to SBOMs plus upgrade SLAs. Scan in CI so flaws die before deploy.",
 "img_i": {"kind": "stack", "title": "Request armor", "rows": [{"label": "Validate input", "sub": "allowlist shapes"}, {"label": "Check ownership", "sub": "every object, server-side"}, {"label": "Encode output + CSP", "sub": "scripts can't run"}]},
 "advanced": "Enterprise nuance: 30-minute threat models per feature (data flows, trust boundaries, abuse cases — cheapest bugs are never written), SAST in pull requests tuned so developers don't ignore it, DAST against staging, SCA gating dependency risk, security champions embedded per dev team translating findings into accepted tickets, and bug bounty scoped to crown jewels only after basics are solid. Measure flaw density and mean time to remediate criticals.",
 "img_a": {"kind": "arch", "title": "Shift-left pipeline", "boxes": [{"label": "Design: threat model", "sub": "30 min per feature"}, {"label": "Code: SAST + champions", "sub": "in the PR"}, {"label": "Release: DAST + SCA gates", "sub": "block on critical"}]},
 "diagram": {"kind": "gates", "title": "Every request passes 4 gates", "gates": [
   {"label": "Gate 1: input shape OK?", "sub": "reject weird payloads", "check": True},
   {"label": "Gate 2: logged in as owner?", "sub": "per-object check", "check": True},
   {"label": "Gate 3: query parameterized?", "sub": "no string concat", "check": True},
   {"label": "Gate 4: output encoded?", "sub": "scripts can't run", "check": True}]}},

"cloud": {
 "beginner": "WHAT: Cloud means renting computers from Amazon, Microsoft, or Google. They secure the buildings; YOU secure your rooms (settings). Most cloud breaches are open doors customers left: public storage buckets, database ports open to the world, passwords pasted in code. WHY it matters: one wrong click can publish private data to the entire planet in seconds — and scanners find it within minutes.",
 "img_b": {"kind": "pipeline", "title": "One click to worldwide", "steps": ["Bucket set public", "Scanners index it", "Data downloaded"]},
 "intermediate": "HOW to stay shut: MFA on root and admin accounts with zero long-lived keys lying around; storage private by default with regular public-exposure audits; security groups allowing only needed ports (never 0.0.0.0/0 on SSH/RDP/databases); audit logging switched on, centralized, and actually reviewed; IaC and repos scanned for secrets before deploy. Run the five-item checklist in this room against any account you own — most people fail at least one.",
 "img_i": {"kind": "stack", "title": "Lockdown order", "rows": [{"label": "Identity: MFA + no stray keys", "sub": "first, always"}, {"label": "Network: private + tight groups", "sub": "no 0.0.0.0/0 admin"}, {"label": "Data: private buckets + keys", "sub": "audit monthly"}]},
 "advanced": "Enterprise nuance: landing-zone guardrails where policies make public buckets structurally impossible; CSPM scanning continuously with minutes-to-alert on drift; secrets managers with rotation; private endpoints instead of internet gateways; cloud-native detection content (impossible-travel logins, root key creation, logging disabled, mass snapshot sharing). Rehearse the leaked-key drill until revocation takes minutes. Measure percentage of resources passing the CIS cloud benchmark.",
 "img_a": {"kind": "arch", "title": "Guardrails over reviews", "boxes": [{"label": "Prevent: policy as code", "sub": "bad config un-deployable"}, {"label": "Detect: CSPM + alerts", "sub": "drift in minutes"}, {"label": "Respond: key drill", "sub": "revoke in minutes"}]},
 "diagram": {"kind": "splitbar", "title": "Who secures what?", "left": "Provider", "right": "YOU", "pct": 30}},

"hardening": {
 "beginner": "WHAT: Hardening strips a system down to only what it needs: no Telnet sending passwords in cleartext, no SMBv1 carrying wormable exploits, no forgotten admin accounts, no default passwords. A minimal system has minimal holes. WHY it matters: attackers adore defaults and leftovers — 'admin/admin' still works somewhere right now, and every unneeded service is a free attack path.",
 "img_b": {"kind": "pipeline", "title": "Shrink to survive", "steps": ["List everything running", "Remove the unneeded", "Lock the rest"]},
 "intermediate": "HOW in practice: disable unused services, roles, and legacy protocols; set host firewalls to default-deny inbound with only documented ports allowed; apply CIS benchmark baselines through automation rather than memory; cut local administrators to a minimum with unique per-host passwords; then re-verify after every change because drift is constant — today's gold image is next quarter's legacy. Pair with monitoring: a hardened host suddenly running new services is itself an alert.",
 "img_i": {"kind": "stack", "title": "Hardening pass", "rows": [{"label": "Remove: services, protocols", "sub": "Telnet, SMBv1, bloat"}, {"label": "Close: default-deny firewall", "sub": "documented ports only"}, {"label": "Set: CIS baselines", "sub": "automated, verified"}]},
 "advanced": "Enterprise nuance: versioned gold images rebuilt on schedule; drift detection with auto-remediation; CIS level profiles matched to tier (stricter where data is hotter); a written exception register with owners and expiry dates — undocumented exceptions are vulnerabilities with extra steps. Measure benchmark pass percentage per fleet, unauthorized-change counts, and mean time to remediate drift. Never harden production on Friday evening.",
 "img_a": {"kind": "arch", "title": "Hardening that sticks", "boxes": [{"label": "Build: gold images", "sub": "versioned, CIS-based"}, {"label": "Enforce: automation", "sub": "drift auto-fixed"}, {"label": "Except: written + expiring", "sub": "owned, reviewed"}]},
 "diagram": {"kind": "beforeafter", "title": "Same server, hardened", "before": ["Telnet open", "SMBv1 on", "admin/admin works", "all ports answer"], "after": ["SSH keys only", "SMBv1 removed", "unique passwords", "default-deny firewall"]}},

"forensics": {
 "beginner": "WHAT: Forensics is detective work after something bad: what happened, in what order, through which door. Clues hide in file timestamps, auto-start lists, browser history, and live memory. WHY it matters: without proof you cannot fix the real entry point, answer leadership, or take legal action — guessing wastes the one chance evidence gives you. Forensics turns 'we were hacked' into exactly how, when, and through which door.",
 "img_b": {"kind": "pipeline", "title": "Clues everywhere", "steps": ["File times changed", "Program auto-starts", "Browser visited lure"]},
 "intermediate": "HOW, respecting volatility (memory dies at power-off, disk persists): capture RAM first, then image disks through write-blockers into hash-verified copies you actually analyze — never the originals. Read registry Run keys for persistence, Prefetch for proof a program RAN plus how often, MFT timestamps for mass-encryption bursts, browser history for the exact phish-click moment. Fuse everything into one timeline where cause precedes effect; corroborate each claim with two artifacts, never one.",
 "img_i": {"kind": "stack", "title": "Capture order", "rows": [{"label": "1st: RAM + network state", "sub": "vanishes on power-off"}, {"label": "2nd: disk image", "sub": "hashed, verified copy"}, {"label": "3rd: logs + artifacts", "sub": "then timeline"}]},
 "advanced": "Enterprise nuance: chain-of-custody forms (who touched evidence, when, with which tool), central timeline tooling across hosts, memory congruity checks for rootkits, legal-hold coordination before wiping anything, and rehearsed evidence-handling roles. Report in the shape decisions need: executive summary, timeline, finding per question asked, gaps admitted, recommendations owned. Metric: evidence completeness and timeline accuracy at peer review.",
 "img_a": {"kind": "arch", "title": "Court-ready process", "boxes": [{"label": "Preserve: custody + hashes", "sub": "defensible copies"}, {"label": "Prove: two artifacts each", "sub": "no single-source claims"}, {"label": "Present: timeline story", "sub": "decisions enabled"}]},
 "diagram": {"kind": "timeline", "title": "Breach night, reconstructed", "events": [
   {"t": "21:02", "label": "phish clicked"},
   {"t": "21:09", "label": "payload ran"},
   {"t": "21:40", "label": "persistence set"},
   {"t": "02:15", "label": "mass encrypt"}]}},

"automation": {
 "beginner": "WHAT: Analysts drown in repetition — same enrichment lookups, same tickets, same blocks at 3 AM. Automation (scripts first, SOAR playbooks later) does the boring parts so humans spend judgment where it counts. WHY it matters: faster response, fewer 3 AM mistakes, and every automated step is logged identically — consistency humans can't match. Start tiny: one script that enriches one alert type, used daily, beats a grand platform nobody maintains.",
 "img_b": {"kind": "pipeline", "title": "Boring work, automated", "steps": ["Alert fires", "Machine gathers context", "Human decides damage"]},
 "intermediate": "HOW to climb safely: level 1 enriches (hash to report link, IP to reputation, user to manager) and drafts tickets — zero damage risk. Level 2 acts reversibly (quarantine the mail, disable the link) behind one-click approval. Level 3 auto-contains only proven, false-positive-free cases with instant rollback. Keep secrets in vaults, rate-limit API calls, make steps idempotent so re-runs are safe, and always include dry-run modes. This tool demonstrates the pattern: detectors plus scoring plus mail plus your review.",
 "img_i": {"kind": "stack", "title": "Automation maturity", "rows": [{"label": "L1: enrich + draft", "sub": "safe, start here"}, {"label": "L2: act with approval", "sub": "reversible steps"}, {"label": "L3: auto-contain", "sub": "proven rules only"}]},
 "advanced": "Enterprise nuance: playbooks versioned and tested in staging against replayed alerts; human-on-the-loop retained for anything destructive; every automated action audit-logged; chaos-testing of playbooks; honest ROI math of analyst-minutes saved versus maintenance hours and false-positive incidents caused — retire playbooks that cost more than they save. Measure MTTR drop and automation FP rate side by side.",
 "img_a": {"kind": "arch", "title": "Playbook anatomy", "boxes": [{"label": "Trigger + conditions", "sub": "precise firing rules"}, {"label": "Steps + rollback", "sub": "reversible by design"}, {"label": "Owner + audit log", "sub": "maintained, provable"}]},
 "diagram": {"kind": "loop", "title": "Automation that never sleeps", "steps": ["Alert fires", "Machine enriches", "Ticket drafted", "Human approves"], "gate": "approve destructive actions"}},

"frameworks": {
 "beginner": "WHAT: Frameworks are shared maps so every team speaks one language. ATT&CK lists attacker tricks with IDs (T1110 password guessing). The Kill Chain lists seven attack stages. NIST describes what a complete program covers. CIS lists must-do safeguards in priority order. WHY it matters: maps stop random defending — you cover terrain systematically and can PROVE what is covered and what is not.",
 "img_b": {"kind": "pipeline", "title": "Pick the right map", "steps": ["HOW they act? ATT&CK", "WHERE to break? Kill Chain", "WHAT first? CIS"]},
 "intermediate": "HOW to use each: map every detection to its ATT&CK technique (this tool prints them — collect them into a heatmap and the red cells become your backlog); review NIST CSF's six functions — Govern, Identify, Protect, Detect, Respond, Recover — for program gaps; apply CIS IG1 essentials first as the small-team survival kit; place Kill Chain breaks deliberately (killing delivery OR command-and-control each defeat the whole chain). D3FEND then converts gaps into engineered countermeasure shopping lists.",
 "img_i": {"kind": "stack", "title": "From map to action", "rows": [{"label": "Map detections to ATT&CK", "sub": "heat-map the gaps"}, {"label": "Score CSF functions 1-4", "sub": "fund the lowest"}, {"label": "Apply CIS IG1", "sub": "survival kit first"}]},
 "advanced": "Enterprise nuance: ATT&CK heatmaps driving the detection backlog quarter by quarter; CSF target profiles per business unit with evidence behind self-scores; CIS auto-assessed by scanners; NIST SP 800-61 setting the response rhythm from Room 8. Present frameworks to leadership as coverage math — technique coverage percentage, CSF maturity trend, IG1 pass rate — and reassess yearly or after every major incident, whichever comes first.",
 "img_a": {"kind": "arch", "title": "Reporting with maps", "boxes": [{"label": "Coverage % per technique", "sub": "detection backlog"}, {"label": "CSF maturity trend", "sub": "program direction"}, {"label": "IG1 pass rate", "sub": "basics proven"}]},
 "diagram": {"kind": "mindmap", "title": "Security maps, one view", "center": "Defend the org", "arms": [
   {"label": "ATT&CK", "sub": "how they act"},
   {"label": "Kill Chain", "sub": "where to break"},
   {"label": "NIST CSF", "sub": "program complete?"},
   {"label": "CIS", "sub": "what first?"}]}},
}
