"""Real incidents + a-day-in-the-life per room. ASCII only."""

STORIES = {
"sec-fund": {"story": "Target 2013: attackers stole HVAC vendor credentials, walked an unsegmented network into POS systems, and stole 40M cards. Every ring failed at once — third-party access, flat network, ignored alerts. One missing control is a gap; all missing is a breach.",
 "day": "Morning: review overnight HIGHs. Midday: approve two firewall exceptions (with expiry). Afternoon: chase one team still on SMS-MFA. The job is rings, daily."},
"net-sec": {"story": "WannaCry 2017: one unpatched SMBv1 hole + open port 445, and a worm encrypted 200,000+ machines including UK hospitals. The patch existed for 59 days. The lesson touring every classroom since: close and patch what faces the world.",
 "day": "Check firewall change queue, review blocked RDP attempts from overnight, verify no new internet-facing admin ports appeared in the scan diff."},
"endpoint": {"story": "UK NHS during WannaCry: unpatched Windows XP on medical devices, no tested offline backups in places — surgeries cancelled, ambulances diverted. Endpoints decide whether malware is an incident or a catastrophe.",
 "day": "Push KEV patches to pilot ring, chase the 3% hosts EDR never reported from (blind spots first), verify last night's backup restores."},
"iam": {"story": "Colonial Pipeline 2021: one legacy VPN account, password-only, no MFA — fuel for the US East Coast disrupted, $4.4M ransom. A single password-only remote door into critical infrastructure.",
 "day": "Review privileged elevation logs, kill two orphaned contractor accounts, nudge the last 5 admins off SMS codes."},
"monitoring": {"story": "Target again: their tools FIRED alerts on the intrusion — humans, drowning in noise, missed them. Monitoring without tuned, owned alerting is decoration.",
 "day": "Clear the overnight queue, tune the one rule that spammed 400 FPs, confirm all domain controllers are still shipping logs."},
"siem": {"story": "Capital One 2019: a misconfigured WAF + SSRF let one person read 100M records from cloud storage. The logs existed — correlation and cloud-aware content did not. SIEM value is joining weak signals across sources.",
 "day": "Write one correlation rule from yesterday's incident, test it on 30 days of history, attach runbook, ship alert-only."},
"soc-ops": {"story": "Equifax 2017: knew about the Struts flaw, didn't patch for 2 months, and an expired certificate blinded their monitoring. 147M records. Triage, patching, and certificate hygiene — all L1-visible failures.",
 "day": "Work the queue oldest-first, escalate one genuine account-takeover with full timeline, close ten scanner-noise FPs with notes."},
"ir": {"story": "Maersk vs NotPetya 2017: 4,000 servers and 45,000 PCs wiped — rebuilt in 10 days because offline backups and a rehearsed rebuild plan existed. Recovery speed, not prevention, saved the company.",
 "day": "Quarterly tabletop: this time, ransomware in backups vendor. Update the call tree — two numbers are stale."},
"threat-det": {"story": "SolarWinds 2020: intruders dwelled for months using legitimate tools (living off the land) — hash-blocklists never stood a chance. Behavior-first detections (impossible travel, odd SAML usage) eventually exposed them.",
 "day": "Hunt hypothesis of the week ('OAuth abuse in our tenant'), encode last week's win as a tested rule, retire one dead IOC feed."},
"malware": {"story": "NotPetya first spread as a poisoned accounting-software update — trusted channel, devastating payload, $10B damage. Delivery through trust is why signatures and sandboxing both matter.",
 "day": "Review sandbox detonations from overnight mail, check canary files are untouched, verify backup restore test passed."},
"phish-email": {"story": "Twitter 2020: phone spear-phishing of employees handed attackers internal tools — 130 accounts, $120K in bitcoin, stock wobble. No malware at all — just persuasion plus weak internal MFA.",
 "day": "Release three quarantined mails after header review, push one new display-name spoof rule, check report-vs-click rate."},
"vuln-mgmt": {"story": "Log4Shell Dec 2021: one logging library inside thousands of apps, CVSS 10, exploited within hours worldwide. Teams with SBOMs found their exposure in a day; others took weeks.",
 "day": "Morning KEV check, push emergency patch to internet-facing Java hosts, update exception register (two expired)."},
"ti": {"story": "During Log4Shell, the teams winning were those whose intel told them WHICH of their assets were exposed and HOW exploitation looked — turning a global panic into a sorted worklist in hours.",
 "day": "Read overnight CISA/ISAC notes, convert one relevant TTP into a hunt, expire 200 stale IOCs."},
"net-det": {"story": "Marriott breach ran ~4 years partly because unusual database queries blended into noise nobody baselined. Anomaly detection exists for exactly this: know normal, spot the deviation.",
 "day": "Review NDR anomalies (two beacons worth hunting), check DNS tunnel dashboard, pull one pcap for the escalation."},
"appsec": {"story": "Equifax (again): Struts CVE-2017-5638, a single unpatched input handler, 147M records. One injection flaw in one framework, internet-facing, unpatched — the AppSec nightmare in one line.",
 "day": "Review SAST findings on two PRs, verify staging DAST is green, chase one team past SLA on a critical."},
"cloud": {"story": "Capital One: SSRF fooled a misconfigured WAF into handing over cloud credentials, then S3 was wide open — 100M records. Cloud breach recipe: one config error plus excessive permissions.",
 "day": "Check CSPM drift alerts (one new public bucket — revert), review root key age, confirm CloudTrail logging intact."},
"hardening": {"story": "Mirai 2016: 600,000 IoT devices enslaved using 61 factory default passwords over Telnet — the botnet then broke DynDNS and half the US internet. Defaults at scale are weapons. Harden or be harnessed.",
 "day": "Scan for Telnet/SNMP defaults on new devices, verify CIS drift report is clean, document one legacy exception."},
"forensics": {"story": "Silk Road takedown: agents arrested Ross Ulbricht mid-session at a library specifically to seize his laptop LIVE — powered-off, the encrypted evidence (and keys in RAM) would have vanished. Volatility order in action.",
 "day": "Image one suspect drive (write-blocked, hashed), update the Robbery-night timeline with browser artifacts."},
"automation": {"story": "CrowdStrike July 2024: a bad sensor update auto-deployed worldwide grounded planes and hospitals — automation with blast radius and no staged rollout. Automate like every run can ruin Friday.",
 "day": "Review playbook runs (one FP auto-block — tune threshold), test new enrichment in staging, check secrets rotation."},
"frameworks": {"story": "After major breaches, the firms recovering fastest briefed boards with maps: ATT&CK heatmaps showing exactly which techniques failed and which held. Maps turn panic into a funded backlog.",
 "day": "Update technique coverage heatmap, score one CSF function with evidence, close one IG1 gap."},
}
